{-# LANGUAGE OverloadedStrings #-}

-- | Test generation for FFI functions
--
-- This module generates .can test files that use the Test framework,
-- providing a Canopy-based testing system that integrates with the compiler pipeline.

module Foreign.TestGenerator
  ( TestConfig(..)
  , generateTestSuite
  , defaultTestConfig
  ) where

import qualified Data.Text as Text
import Data.Text (Text)
import qualified Data.Map.Strict as Map
import Data.Map.Strict (Map)

import Foreign.FFI (FFIFunction(..), FFIType(..))

-- | Configuration for test generation
data TestConfig = TestConfig
  { _testPropertyRuns :: !Int      -- ^ Number of property test runs
  , _testEdgeCases :: !Bool        -- ^ Include edge case tests
  , _testPerformance :: !Bool      -- ^ Include performance tests
  , _testIntegration :: !Bool      -- ^ Include integration tests
  , _testMemoryUsage :: !Bool      -- ^ Include memory usage tests
  , _testErrorInjection :: !Bool   -- ^ Include error injection tests
  } deriving (Eq, Show)

-- | Default test configuration
defaultTestConfig :: TestConfig
defaultTestConfig = TestConfig
  { _testPropertyRuns = 100
  , _testEdgeCases = True
  , _testPerformance = True
  , _testIntegration = True
  , _testMemoryUsage = True
  , _testErrorInjection = True
  }

-- | Generate a complete test suite for all FFI functions
generateTestSuite :: TestConfig -> Map Text FFIFunction -> Text
generateTestSuite config functions = Text.unlines
  [ generateCanopyTestHeader config functions
  , Text.unlines (map (generateCanopyFunctionTests config) (Map.toList functions))
  , generateCanopyTestRunner config functions
  ]

-- | Generate Canopy test module header with imports
generateCanopyTestHeader :: TestConfig -> Map Text FFIFunction -> Text
generateCanopyTestHeader _config functions = Text.unlines
  [ "-- | Auto-generated FFI tests for Canopy"
  , "-- Generated by canopy test-ffi command"
  , ""
  , "module FFITests exposing (main, runAllTests)"
  , ""
  , "import Test exposing (Test, describe, test, expect, equal)"
  , ""
  , "-- Import FFI modules being tested"
  , Text.unlines (map generateFFIImport (Map.keys functions))
  , ""
  , "-- | Main entry point for JavaScript execution"
  , "main : String"
  , "main = \"FFI Tests Ready\""
  , ""
  ]

-- | Generate import for FFI module (simplified for now)
generateFFIImport :: Text -> Text
generateFFIImport functionName =
  "-- import " <> functionName <> " (FFI function will be imported here)"

-- | Generate tests for a single FFI function in Canopy
generateCanopyFunctionTests :: TestConfig -> (Text, FFIFunction) -> Text
generateCanopyFunctionTests config (name, function) = Text.unlines
  [ ""
  , "-- Tests for " <> name
  , "test" <> name <> " : Test"
  , "test" <> name <> " ="
  , "    describe \"" <> name <> " FFI function\""
  , "        [ " <> generateCanopyBasicTest name function
  , "        , " <> generateCanopyTypeTest name function
  , "        , " <> generateCanopyPropertyTest config name function
  , "        ]"
  , ""
  ]

-- | Generate a basic functionality test in Canopy
--
-- Produces a test that calls the FFI function with default arguments
-- and verifies it returns a value, using 'generateCallExpression'.
generateCanopyBasicTest :: Text -> FFIFunction -> Text
generateCanopyBasicTest name function = Text.unlines
  [ "test \"" <> name <> " basic functionality\" <|"
  , "            \\_ ->"
  , "                " <> generateCallExpression name function
  ]

-- | Generate type validation test in Canopy
--
-- Produces a test that validates the output type of the FFI function,
-- using 'generateTypeAssertion'.
generateCanopyTypeTest :: Text -> FFIFunction -> Text
generateCanopyTypeTest name function = Text.unlines
  [ "test \"" <> name <> " type validation\" <|"
  , "            \\_ ->"
  , "                -- Type: " <> renderFunctionType function
  , "                " <> generateTypeAssertion name function
  ]

-- | Generate property-based test in Canopy
--
-- Produces a boundary/property test that exercises edge cases of the FFI
-- function, using 'generateBoundaryTest'.
generateCanopyPropertyTest :: TestConfig -> Text -> FFIFunction -> Text
generateCanopyPropertyTest config name function = Text.unlines
  [ "test \"" <> name <> " property test (" <> Text.pack (show (_testPropertyRuns config)) <> " runs)\" <|"
  , "            \\_ ->"
  , "                " <> generateBoundaryTest name function
  ]

-- | Generate the main test runner in Canopy
generateCanopyTestRunner :: TestConfig -> Map Text FFIFunction -> Text
generateCanopyTestRunner _config functions = Text.unlines
  [ "-- | Run all FFI tests"
  , "runAllTests : Test"
  , "runAllTests ="
  , "    describe \"FFI Test Suite\""
  , "        [ " <> Text.intercalate "\n        , " (map (\name -> "test" <> name) (Map.keys functions))
  , "        ]"
  ]

-- | Helper function to render function type for documentation
renderFunctionType :: FFIFunction -> Text
renderFunctionType (FFIFunction inputTypes outputType _) =
  let inputText = Text.intercalate " -> " (map renderFFIType inputTypes)
      outputText = renderFFIType outputType
  in if null inputTypes
     then outputText
     else inputText <> " -> " <> outputText

-- | Helper function to render FFI types with correct qualified namespaces
renderFFIType :: FFIType -> Text
renderFFIType ffiType = case ffiType of
  FFIBasic typeName -> typeName
  FFIFunctionType params returnType ->
    "(" <> Text.intercalate " -> " (map renderFFIType params) <> " -> " <> renderFFIType returnType <> ")"
  FFIList elementType -> "List " <> renderFFIType elementType
  FFIMaybe valueType -> "Maybe " <> renderFFIType valueType
  FFIResult errorType valueType -> "Result " <> renderFFIType errorType <> " " <> renderFFIType valueType
  FFITask errorType valueType -> "Task " <> renderFFIType errorType <> " " <> renderFFIType valueType
  FFITuple tupleTypes -> "(" <> Text.intercalate ", " (map renderFFIType tupleTypes) <> ")"
  FFIRecord _fields -> "Record"
  FFIOpaque typeName -> typeName

-- | Generate a call expression that invokes the FFI function with default
-- arguments and asserts the result via 'outputAssertion'.
--
-- For a function @add : Int -> Int -> Int@ this produces:
--
-- > let result = add 0 0
-- > in expect (Debug.toString result |> String.length) |> Expect.greaterThan 0
generateCallExpression :: Text -> FFIFunction -> Text
generateCallExpression name (FFIFunction inputTypes outputType _) =
  Text.unlines
    [ "let result = " <> name <> " " <> defaultArgs
    , "                in " <> outputAssertion outputType
    ]
  where
    defaultArgs =
      Text.intercalate " " (map defaultValueForType inputTypes)

-- | Generate a type assertion that validates the output type of the function.
--
-- Calls the function with defaults and then inspects the result using
-- 'typeAssertionForOutput' to confirm the correct type variant is returned.
generateTypeAssertion :: Text -> FFIFunction -> Text
generateTypeAssertion name (FFIFunction inputTypes outputType _) =
  Text.unlines
    [ "let result = " <> name <> " " <> defaultArgs
    , "                in " <> typeAssertionForOutput outputType
    ]
  where
    defaultArgs =
      Text.intercalate " " (map defaultValueForType inputTypes)

-- | Generate a boundary test that exercises edge-case inputs.
--
-- Uses the function's input types to select boundary values (empty strings,
-- zero, empty lists, etc.) and asserts the output is non-trivial.
generateBoundaryTest :: Text -> FFIFunction -> Text
generateBoundaryTest name (FFIFunction inputTypes outputType _) =
  Text.unlines
    [ "let result = " <> name <> " " <> boundaryArgs
    , "                in " <> outputAssertion outputType
    ]
  where
    boundaryArgs =
      Text.intercalate " " (map boundaryValueForType inputTypes)

-- | Produce an assertion expression for a given output type.
--
-- For wrapper types like 'FFIResult' and 'FFIMaybe' the generated code
-- pattern-matches on the success/presence variant and verifies the serialised
-- representation is non-empty, while the error/absence variant is checked
-- with an identity assertion.
outputAssertion :: FFIType -> Text
outputAssertion outputType =
  case outputType of
    FFIResult _ _ ->
      Text.unlines
        [ "case result of"
        , "                    Ok v -> expect (Debug.toString v |> String.length) |> Expect.greaterThan 0"
        , "                    Err e -> expect (Debug.toString e |> String.length) |> Expect.greaterThan 0"
        ]
    FFIMaybe _ ->
      Text.unlines
        [ "case result of"
        , "                    Just v -> expect (Debug.toString v |> String.length) |> Expect.greaterThan 0"
        , "                    Nothing -> expect \"Nothing variant\" |> equal \"Nothing variant\""
        ]
    _ ->
      "expect (Debug.toString result |> String.length) |> Expect.greaterThan 0"

-- | Produce a type-level assertion for a given output type.
--
-- Similar to 'outputAssertion' but focused on confirming the correct type
-- variant was returned rather than inspecting the payload.
typeAssertionForOutput :: FFIType -> Text
typeAssertionForOutput outputType =
  case outputType of
    FFIResult _ _ ->
      Text.unlines
        [ "case result of"
        , "                    Ok v -> expect (Debug.toString v |> String.length) |> Expect.greaterThan 0"
        , "                    Err _ -> expect \"Error variant\" |> equal \"Error variant\""
        ]
    FFIMaybe _ ->
      Text.unlines
        [ "case result of"
        , "                    Just v -> expect (Debug.toString v |> String.length) |> Expect.greaterThan 0"
        , "                    Nothing -> expect \"Nothing variant\" |> equal \"Nothing variant\""
        ]
    _ ->
      "expect (Debug.toString result |> String.length) |> Expect.greaterThan 0"

-- | Produce a default value literal for a given FFI type.
--
-- Used to construct function calls with safe placeholder arguments.
defaultValueForType :: FFIType -> Text
defaultValueForType ffiType =
  case ffiType of
    FFIBasic "String"  -> "\"\""
    FFIBasic "Int"     -> "0"
    FFIBasic "Float"   -> "0.0"
    FFIBasic "Bool"    -> "False"
    FFIBasic _         -> "\"\""
    FFIList _          -> "[]"
    FFIMaybe _         -> "Nothing"
    FFIResult _ _      -> "(Ok \"\")"
    FFITask _ _        -> "(Task.succeed \"\")"
    FFITuple types     -> "(" <> Text.intercalate ", " (map defaultValueForType types) <> ")"
    FFIFunctionType _ _ -> "(\\_ -> \"\")"
    FFIRecord _        -> "{}"
    FFIOpaque _        -> "\"\""

-- | Produce a boundary/edge-case value literal for a given FFI type.
--
-- Selects values that are likely to trigger edge cases: empty strings, zero,
-- empty collections, etc.
boundaryValueForType :: FFIType -> Text
boundaryValueForType ffiType =
  case ffiType of
    FFIBasic "String"  -> "\"\""
    FFIBasic "Int"     -> "-1"
    FFIBasic "Float"   -> "-0.0"
    FFIBasic "Bool"    -> "True"
    FFIBasic _         -> "\"\""
    FFIList _          -> "[]"
    FFIMaybe _         -> "Nothing"
    FFIResult _ _      -> "(Err \"boundary\")"
    FFITask _ _        -> "(Task.fail \"boundary\")"
    FFITuple types     -> "(" <> Text.intercalate ", " (map boundaryValueForType types) <> ")"
    FFIFunctionType _ _ -> "(\\_ -> \"\")"
    FFIRecord _        -> "{}"
    FFIOpaque _        -> "\"\""