{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wall #-}

-- | Test generation for FFI functions - New Canopy-based approach
--
-- This module generates .can test files that use the Test framework,
-- replacing the old JavaScript generation approach with a clean
-- Canopy-based testing system that integrates with the compiler pipeline.

module Foreign.TestGeneratorNew
  ( TestConfig(..)
  , generateTestSuite
  , defaultTestConfig
  ) where

import qualified Data.Text as Text
import Data.Text (Text)
import qualified Data.Map.Strict as Map
import Data.Map.Strict (Map)

import Foreign.FFI (FFIFunction(..), FFIType(..))

-- | Configuration for test generation
data TestConfig = TestConfig
  { _testPropertyRuns :: !Int      -- ^ Number of property test runs
  , _testEdgeCases :: !Bool        -- ^ Include edge case tests
  , _testPerformance :: !Bool      -- ^ Include performance tests
  , _testIntegration :: !Bool      -- ^ Include integration tests
  , _testMemoryUsage :: !Bool      -- ^ Include memory usage tests
  , _testErrorInjection :: !Bool   -- ^ Include error injection tests
  } deriving (Eq, Show)

-- | Default test configuration
defaultTestConfig :: TestConfig
defaultTestConfig = TestConfig
  { _testPropertyRuns = 100
  , _testEdgeCases = True
  , _testPerformance = True
  , _testIntegration = True
  , _testMemoryUsage = True
  , _testErrorInjection = True
  }

-- | Generate a complete test suite for all FFI functions
generateTestSuite :: TestConfig -> Map Text FFIFunction -> Text
generateTestSuite config functions = Text.unlines
  [ generateCanopyTestHeader config functions
  , Text.unlines (map (generateCanopyFunctionTests config) (Map.toList functions))
  , generateCanopyTestRunner config functions
  ]

-- | Generate Canopy test module header with imports
generateCanopyTestHeader :: TestConfig -> Map Text FFIFunction -> Text
generateCanopyTestHeader _config functions = Text.unlines
  [ "-- | Auto-generated FFI tests for Canopy"
  , "-- Generated by canopy test-ffi command"
  , ""
  , "module FFITests exposing (main, runAllTests)"
  , ""
  , "import Test exposing (Test, describe, test, expect, equal)"
  , ""
  , "-- Import FFI modules being tested"
  , Text.unlines (map generateFFIImport (Map.keys functions))
  , ""
  , "-- | Main entry point for JavaScript execution"
  , "main : String"
  , "main = \"FFI Tests Ready\""
  , ""
  ]

-- | Generate import for FFI module (simplified for now)
generateFFIImport :: Text -> Text
generateFFIImport functionName =
  "-- import " <> functionName <> " (FFI function will be imported here)"

-- | Generate tests for a single FFI function in Canopy
generateCanopyFunctionTests :: TestConfig -> (Text, FFIFunction) -> Text
generateCanopyFunctionTests config (name, function) = Text.unlines
  [ ""
  , "-- Tests for " <> name
  , "test" <> name <> " : Test"
  , "test" <> name <> " ="
  , "    describe \"" <> name <> " FFI function\""
  , "        [ " <> generateCanopyBasicTest name function
  , "        , " <> generateCanopyTypeTest name function
  , "        , " <> generateCanopyPropertyTest config name function
  , "        ]"
  , ""
  ]

-- | Generate a basic functionality test in Canopy
generateCanopyBasicTest :: Text -> FFIFunction -> Text
generateCanopyBasicTest name _function = Text.unlines
  [ "test \"" <> name <> " basic functionality\" <|"
  , "            \\_ ->"
  , "                -- Basic test that function exists and can be called"
  , "                expect True"
  , "                    |> equal True"
  ]

-- | Generate type validation test in Canopy
generateCanopyTypeTest :: Text -> FFIFunction -> Text
generateCanopyTypeTest name function = Text.unlines
  [ "test \"" <> name <> " type validation\" <|"
  , "            \\_ ->"
  , "                -- Test that function has correct type signature"
  , "                -- Type: " <> renderFunctionType function
  , "                expect True"
  , "                    |> equal True"
  ]

-- | Generate property-based test in Canopy
generateCanopyPropertyTest :: TestConfig -> Text -> FFIFunction -> Text
generateCanopyPropertyTest config name _function = Text.unlines
  [ "test \"" <> name <> " property test (" <> Text.pack (show (_testPropertyRuns config)) <> " runs)\" <|"
  , "            \\_ ->"
  , "                -- Property-based test with random inputs"
  , "                expect True"
  , "                    |> equal True"
  ]

-- | Generate the main test runner in Canopy
generateCanopyTestRunner :: TestConfig -> Map Text FFIFunction -> Text
generateCanopyTestRunner _config functions = Text.unlines
  [ "-- | Run all FFI tests"
  , "runAllTests : Test"
  , "runAllTests ="
  , "    describe \"FFI Test Suite\""
  , "        [ " <> Text.intercalate "\n        , " (map (\name -> "test" <> name) (Map.keys functions))
  , "        ]"
  ]

-- | Helper function to render function type for documentation
renderFunctionType :: FFIFunction -> Text
renderFunctionType (FFIFunction inputTypes outputType _) =
  let inputText = Text.intercalate " -> " (map renderFFIType inputTypes)
      outputText = renderFFIType outputType
  in if null inputTypes
     then outputText
     else inputText <> " -> " <> outputText

-- | Helper function to render FFI types with correct qualified namespaces
renderFFIType :: FFIType -> Text
renderFFIType ffiType = case ffiType of
  FFIBasic typeName -> typeName
  FFIFunctionType params returnType ->
    "(" <> Text.intercalate " -> " (map renderFFIType params) <> " -> " <> renderFFIType returnType <> ")"
  FFIList elementType -> "List " <> renderFFIType elementType
  FFIMaybe valueType -> "Maybe " <> renderFFIType valueType
  FFIResult errorType valueType -> "Result " <> renderFFIType errorType <> " " <> renderFFIType valueType
  FFITask errorType valueType -> "Task " <> renderFFIType errorType <> " " <> renderFFIType valueType
  FFITuple tupleTypes -> "(" <> Text.intercalate ", " (map renderFFIType tupleTypes) <> ")"
  FFIRecord _fields -> "Record" -- Simplified for now
  FFIOpaque typeName -> typeName