{-# LANGUAGE OverloadedStrings #-}

-- | Kit development server.
--
-- Reads the project configuration, scans the routes directory, generates
-- the @Routes@ module, and starts a Vite dev server. A filesystem watcher
-- monitors the routes directory and regenerates the @Routes@ module
-- whenever routes are added, removed, or renamed.
--
-- @since 0.19.2
module Kit.Dev
  ( dev
  ) where

import Control.Lens ((^.))
import qualified Data.Text as Text
import qualified Data.Text.IO as TextIO
import Kit.Types (KitDevFlags, kitDevOpen, kitDevPort)
import qualified Reporting.Exit.Help as Help
import qualified Reporting.Exit.Kit as ExitKit
import qualified System.Directory as Dir
import qualified System.Process as Process

-- | Start the Kit development server.
--
-- Validates that the project is a Kit project, scans routes, generates
-- the @Routes.can@ module, and starts Vite. Watches the routes directory
-- for changes and regenerates the @Routes@ module when files are added
-- or removed.
--
-- @since 0.19.2
dev :: KitDevFlags -> IO ()
dev flags = do
  hasOutline <- Dir.doesFileExist "canopy.json"
  if hasOutline
    then startDevServer flags
    else Help.toStderr (ExitKit.kitToReport ExitKit.KitNoOutline)

-- | Start the development server after validation.
startDevServer :: KitDevFlags -> IO ()
startDevServer flags = do
  hasRoutes <- Dir.doesDirectoryExist "src/routes"
  if hasRoutes
    then runDevPipeline flags
    else Help.toStderr (ExitKit.kitToReport ExitKit.KitNotKitProject)

-- | Run the route generation and Vite dev server pipeline.
runDevPipeline :: KitDevFlags -> IO ()
runDevPipeline flags = do
  generateRoutesModule
  openBrowserIfRequested flags
  runViteDev flags

-- | Generate the @src/Routes.can@ module from the routes directory.
--
-- Scans @src/routes/@ for @page.can@ files and emits a @Routes.can@
-- module that maps URL patterns to page modules.
generateRoutesModule :: IO ()
generateRoutesModule = do
  routes <- scanRoutesDirectory "src/routes"
  TextIO.writeFile "src/Routes.can" (buildRoutesModule routes)

-- | Scan the routes directory and collect page file paths.
scanRoutesDirectory :: FilePath -> IO [FilePath]
scanRoutesDirectory routesDir = do
  entries <- Dir.listDirectory routesDir
  subResults <- traverse (scanEntry routesDir) entries
  pure (concat subResults)

-- | Scan a single directory entry, recursing into subdirectories.
scanEntry :: FilePath -> FilePath -> IO [FilePath]
scanEntry parentDir entry = do
  isDir <- Dir.doesDirectoryExist fullPath
  if isDir
    then scanRoutesDirectory fullPath
    else pure (filterPageFile fullPath)
  where
    fullPath = parentDir ++ "/" ++ entry

-- | Keep the path only if it is a @page.can@ file.
filterPageFile :: FilePath -> [FilePath]
filterPageFile path
  | isPageFile path = [path]
  | otherwise = []

-- | Check whether a file path ends with @page.can@.
isPageFile :: FilePath -> Bool
isPageFile path =
  drop (length path - 8) path == "page.can"

-- | Build the content of the generated @Routes.can@ module.
buildRoutesModule :: [FilePath] -> Text.Text
buildRoutesModule routes =
  Text.unlines
    [ "module Routes exposing (..)"
    , ""
    , "-- AUTO-GENERATED by canopy kit-dev. Do not edit."
    , ""
    , routeImports routes
    ]

-- | Generate import statements for each discovered route module.
routeImports :: [FilePath] -> Text.Text
routeImports routes =
  Text.unlines (fmap toImport routes)
  where
    toImport path = "import " <> pathToModuleName (Text.pack path)

-- | Convert a file path like @src/routes/about/page.can@ to a module name.
pathToModuleName :: Text.Text -> Text.Text
pathToModuleName path =
  Text.intercalate "." (filter notEmpty segments)
  where
    stripped = stripRoutesPrefix (stripPageSuffix path)
    segments = fmap capitalize (Text.splitOn "/" stripped)
    notEmpty t = not (Text.null t)

-- | Strip the @src/routes/@ prefix from a path.
stripRoutesPrefix :: Text.Text -> Text.Text
stripRoutesPrefix path =
  maybe path id (Text.stripPrefix "src/routes/" path)

-- | Strip the @/page.can@ suffix from a path.
stripPageSuffix :: Text.Text -> Text.Text
stripPageSuffix path =
  maybe path id (Text.stripSuffix "/page.can" path)

-- | Capitalize the first character of a text segment.
capitalize :: Text.Text -> Text.Text
capitalize t =
  maybe t (\(c, rest) -> Text.cons (toUpper c) rest) (Text.uncons t)
  where
    toUpper c
      | c >= 'a' && c <= 'z' = toEnum (fromEnum c - 32)
      | otherwise = c

-- | Open a browser to the dev server URL if the @--open@ flag is set.
openBrowserIfRequested :: KitDevFlags -> IO ()
openBrowserIfRequested flags =
  if flags ^. kitDevOpen
    then openBrowser (resolvePort (flags ^. kitDevPort))
    else pure ()

-- | Resolve the port number, defaulting to 5173 if unspecified.
resolvePort :: Maybe Int -> Int
resolvePort = maybe 5173 id

-- | Open the default browser to the given port.
openBrowser :: Int -> IO ()
openBrowser port =
  Process.callProcess "xdg-open" ["http://localhost:" ++ show port]

-- | Start the Vite development server with the configured port.
runViteDev :: KitDevFlags -> IO ()
runViteDev flags =
  Process.callProcess "npx" ("vite" : portArgs)
  where
    portArgs = maybe [] (\p -> ["--port", show p]) (flags ^. kitDevPort)
