#!/usr/bin/env python3
"""
Analyze debug files generated by golden tests to identify patterns
"""

import os
import sys
import re
from difflib import unified_diff

def analyze_files():
    """Analyze the debug files generated by the test."""
    
    elm_user = "/tmp/debug-elm-user-basic-arithmetic.js"
    canopy_user = "/tmp/debug-canopy-user-basic-arithmetic.js"
    elm_full = "/tmp/debug-elm-full-basic-arithmetic.js"
    canopy_full = "/tmp/debug-canopy-full-basic-arithmetic.js"
    
    # Check if files exist
    for file_path in [elm_user, canopy_user, elm_full, canopy_full]:
        if not os.path.exists(file_path):
            print(f"File not found: {file_path}")
            return
    
    # Read all files
    with open(elm_user, 'r') as f:
        elm_user_content = f.read()
    with open(canopy_user, 'r') as f:
        canopy_user_content = f.read()
    with open(elm_full, 'r') as f:
        elm_full_content = f.read()
    with open(canopy_full, 'r') as f:
        canopy_full_content = f.read()
    
    print("=== FILE SIZE ANALYSIS ===")
    print(f"Elm user code:     {len(elm_user_content):6d} bytes")
    print(f"Canopy user code:  {len(canopy_user_content):6d} bytes")
    print(f"User code diff:    {len(elm_user_content) - len(canopy_user_content):6d} bytes")
    print()
    print(f"Elm full JS:       {len(elm_full_content):6d} bytes")
    print(f"Canopy full JS:    {len(canopy_full_content):6d} bytes")
    print(f"Full JS diff:      {len(elm_full_content) - len(canopy_full_content):6d} bytes")
    
    print("\n=== PATTERN ANALYSIS ===")
    
    # Look for specific patterns
    patterns = [
        ('{{', 'Double braces'),
        ('}};}', 'Closure endings'),
        ('_UNUSED', 'Unused markers'),
        ('function(', 'Function declarations'),
        ('var $', 'Variable declarations'),
        ('return ', 'Return statements'),
        (';', 'Semicolons'),
        ('A2(', 'Arity-2 function calls'),
        ('F2(', 'Arity-2 function wrappers'),
    ]
    
    print("User code patterns:")
    print(f"{'Pattern':<20} {'Elm':<8} {'Canopy':<8} {'Diff':<8}")
    print("-" * 50)
    
    for pattern, description in patterns:
        elm_count = elm_user_content.count(pattern)
        canopy_count = canopy_user_content.count(pattern)
        diff = elm_count - canopy_count
        
        print(f"{description:<20} {elm_count:<8} {canopy_count:<8} {diff:<8}")
    
    print("\n=== FIRST DIFFERENCE ANALYSIS ===")
    
    # Find first difference
    min_len = min(len(elm_user_content), len(canopy_user_content))
    first_diff_pos = -1
    
    for i in range(min_len):
        if elm_user_content[i] != canopy_user_content[i]:
            first_diff_pos = i
            break
    
    if first_diff_pos != -1:
        print(f"First difference at position {first_diff_pos}")
        
        # Show context around the difference
        start = max(0, first_diff_pos - 100)
        end = min(len(elm_user_content), first_diff_pos + 100)
        
        print(f"\nElm context (position {start}-{end}):")
        print(repr(elm_user_content[start:end]))
        
        start = max(0, first_diff_pos - 100)
        end = min(len(canopy_user_content), first_diff_pos + 100)
        
        print(f"\nCanopy context (position {start}-{end}):")
        print(repr(canopy_user_content[start:end]))
        
        # Look for specific patterns around the difference
        analyze_difference_context(elm_user_content, canopy_user_content, first_diff_pos)
    else:
        if len(elm_user_content) != len(canopy_user_content):
            print("Files are identical except for length")
            shorter = min(len(elm_user_content), len(canopy_user_content))
            longer_file = "Elm" if len(elm_user_content) > len(canopy_user_content) else "Canopy"
            longer_content = elm_user_content if len(elm_user_content) > len(canopy_user_content) else canopy_user_content
            
            print(f"{longer_file} has extra content at the end:")
            print(repr(longer_content[shorter:shorter+200]))
        else:
            print("Files are identical")
    
    print("\n=== DETAILED DIFF ANALYSIS ===")
    
    # Create line-by-line diff
    elm_lines = elm_user_content.splitlines()
    canopy_lines = canopy_user_content.splitlines()
    
    # Find differing lines
    diff_lines = list(unified_diff(
        elm_lines, 
        canopy_lines, 
        fromfile='elm', 
        tofile='canopy', 
        lineterm='',
        n=3
    ))
    
    if diff_lines:
        print("First 20 lines of diff:")
        for line in diff_lines[:20]:
            print(line)
    else:
        print("No line-level differences found")
    
    # Look for specific JavaScript patterns
    print("\n=== JAVASCRIPT PATTERN ANALYSIS ===")
    analyze_js_patterns(elm_user_content, canopy_user_content)

def analyze_difference_context(elm_content, canopy_content, pos):
    """Analyze the context around the first difference."""
    
    # Look at a larger window around the difference
    start = max(0, pos - 500)
    end = min(len(elm_content), pos + 500)
    
    elm_window = elm_content[start:end]
    canopy_window = canopy_content[start:min(len(canopy_content), end)]
    
    print(f"\n=== DIFFERENCE CONTEXT ANALYSIS ===")
    
    # Look for common JavaScript patterns
    patterns_to_check = [
        r'function\s+[^(]+\([^)]*\)\s*\{[^}]*\}',  # Function definitions
        r'var\s+\$[^=]+=',  # Variable assignments
        r'\{\{[^}]*\}\}',   # Double brace patterns
        r'return\s+[^;]+;', # Return statements
        r'A\d+\([^)]+\)',   # Arity function calls
    ]
    
    for i, pattern in enumerate(patterns_to_check):
        elm_matches = re.findall(pattern, elm_window)
        canopy_matches = re.findall(pattern, canopy_window)
        
        if len(elm_matches) != len(canopy_matches):
            print(f"Pattern {i+1} difference:")
            print(f"  Elm: {len(elm_matches)} matches")
            print(f"  Canopy: {len(canopy_matches)} matches")
            
            if elm_matches and canopy_matches:
                print(f"  First Elm match: {elm_matches[0][:50]}...")
                print(f"  First Canopy match: {canopy_matches[0][:50]}...")

def analyze_js_patterns(elm_content, canopy_content):
    """Analyze specific JavaScript generation patterns."""
    
    # Check for Elm-specific patterns
    elm_patterns = [
        ('region.I.z', 'Elm region format'),
        ('region.N.z', 'Elm region format'),
        ('/**_UNUSED/', 'Elm unused blocks'),
        ('/**//', 'Elm comment blocks'),
        ('{{var ', 'Elm variable blocks'),
        ('}{};}', 'Elm closure endings'),
    ]
    
    canopy_patterns = [
        ('region.start.line', 'Canopy region format'),
        ('region.end.line', 'Canopy region format'),
    ]
    
    print("Elm-specific patterns:")
    for pattern, desc in elm_patterns:
        elm_count = elm_content.count(pattern)
        canopy_count = canopy_content.count(pattern)
        if elm_count > 0 or canopy_count > 0:
            print(f"  {desc}: Elm={elm_count}, Canopy={canopy_count}")
    
    print("\nCanopy-specific patterns:")
    for pattern, desc in canopy_patterns:
        elm_count = elm_content.count(pattern)
        canopy_count = canopy_content.count(pattern)
        if elm_count > 0 or canopy_count > 0:
            print(f"  {desc}: Elm={elm_count}, Canopy={canopy_count}")
    
    # Look for function wrapper differences
    print("\nFunction wrapper analysis:")
    
    # Check for different function wrapper patterns
    elm_wrapper_pattern = r'\{\{var [^}]+\}\}'
    canopy_wrapper_pattern = r'function\([^)]*\)\s*\{[^}]*\}'
    
    elm_wrappers = re.findall(elm_wrapper_pattern, elm_content)
    canopy_wrappers = re.findall(canopy_wrapper_pattern, canopy_content)
    
    print(f"  Elm double-brace wrappers: {len(elm_wrappers)}")
    print(f"  Canopy function wrappers: {len(canopy_wrappers)}")
    
    if elm_wrappers:
        print(f"  Example Elm wrapper: {elm_wrappers[0][:100]}...")
    if canopy_wrappers:
        print(f"  Example Canopy wrapper: {canopy_wrappers[0][:100]}...")

def main():
    analyze_files()

if __name__ == "__main__":
    main()