---
name: canopy
version: 0.19.1
synopsis: "The `canopy` command line interface."
description: |
  This includes commands like `canopy make`, `canopy repl`, and many others
  for helping make Canopy developers happy and productive.
homepage: "https://github.com/quinten/canopy"
license: BSD-3-Clause
license-file: LICENSE
author: "Quinten Kasteel"
maintainer: "info@canopy-lang.org"
copyright: "Copyright (c) 2025-present, Quinten Kasteel"
category: Compiler, Language

dependencies:
  - ansi-terminal
  - ansi-wl-pprint < 0.7
  - base
  - binary
  - bytestring
  - containers
  - directory
  - edit-distance
  - file-embed
  - filelock
  - filepath
  - ghc-prim
  - haskeline
  - HTTP
  - http-client
  - http-client-tls
  - http-types
  - tls < 2
  - language-glsl
  - language-javascript >= 0.8.0.0
  - lens
  - mtl
  - network
  - crypton-connection
  - parsec
  - filepath
  - process
  - raw-strings-qq
  - scientific
  - SHA
  - snap-core
  - snap-server
  - template-haskell
  - text
  - time
  - unordered-containers
  - utf8-string
  - vector
  - zip-archive
  - fsnotify
  - websockets

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DerivingStrategies
  - DerivingVia
  - DeriveFunctor
  - DeriveGeneric
  - DeriveDataTypeable
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - UndecidableInstances

library:
  source-dirs:
    - compiler/src
    - builder/src
    - terminal/src
    - terminal/impl
  ghc-options:
    - -Wall
    - -fwarn-tabs
    - -O2

executables:
  canopy:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -rtsopts
      - -threaded
      - -Werror=incomplete-patterns
      - -Werror=missing-fields
    dependencies:
      - canopy

tests:
  canopy-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - canopy
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - tasty-golden
      - QuickCheck
      - temporary
      - text
    when:
      - condition: false
        other-modules: Paths_canopy
