{-# LANGUAGE OverloadedStrings #-}

-- | Live reload server for development hot-reloading.
--
-- Provides a lightweight WebSocket-based live reload server that notifies
-- connected browser clients when source files change.  The server
-- maintains a list of connected clients and broadcasts a @\"reload\"@
-- message to all of them when 'notifyClients' is called.
--
-- == Architecture
--
-- The 'LiveReloadServer' holds a thread-safe list of active WebSocket
-- connections.  Browser pages connect by including a small JavaScript
-- snippet (generated by 'liveReloadScript') that opens a WebSocket to
-- the server.  On file change, the build system calls 'notifyClients'
-- to push a reload command to every connected browser.
--
-- Dead connections (client closed tab) are automatically pruned during
-- broadcast.
--
-- == Usage
--
-- @
-- server <- startServer 8234
-- -- ... after recompilation succeeds ...
-- notifyClients server
-- @
--
-- @since 0.19.2
module Watch.LiveReload
  ( -- * Server
    LiveReloadServer,
    startServer,
    stopServer,
    notifyClients,

    -- * Script Injection
    liveReloadScript,

    -- * Error Overlay
    errorOverlayScript,

    -- * Configuration
    defaultPort,
  )
where

import Control.Concurrent (forkIO)
import qualified Control.Concurrent.MVar as MVar
import Control.Exception (IOException)
import qualified Control.Exception as Exception
import qualified Data.ByteString.Lazy.Char8 as LBS8
import qualified Data.Text as Text
import qualified Network.WebSockets as WS

-- | A live reload server managing connected browser clients.
--
-- @since 0.19.2
data LiveReloadServer = LiveReloadServer
  { _lrsPort :: !Int,
    _lrsClients :: !(MVar.MVar [WS.Connection])
  }

-- | Default WebSocket port for live reload.
--
-- @since 0.19.2
defaultPort :: Int
defaultPort = 8234

-- | Start a live reload WebSocket server on the given port.
--
-- The server runs in a background thread and accepts WebSocket
-- connections indefinitely.  Each new connection is added to the
-- client list for later broadcast via 'notifyClients'.
--
-- @since 0.19.2
startServer :: Int -> IO LiveReloadServer
startServer port = do
  clientsRef <- MVar.newMVar []
  let server = LiveReloadServer port clientsRef
  _ <- forkIO (runServer server)
  pure server

-- | Stop the live reload server by disconnecting all clients.
--
-- @since 0.19.2
stopServer :: LiveReloadServer -> IO ()
stopServer server = do
  clients <- MVar.takeMVar (_lrsClients server)
  mapM_ safeClose clients
  MVar.putMVar (_lrsClients server) []

-- | Notify all connected browser clients to reload.
--
-- Sends a @\"reload\"@ text message to every connected WebSocket client.
-- Dead connections are pruned automatically during the broadcast.
--
-- @since 0.19.2
notifyClients :: LiveReloadServer -> IO ()
notifyClients server = do
  clients <- MVar.takeMVar (_lrsClients server)
  alive <- broadcastReload clients
  MVar.putMVar (_lrsClients server) alive

-- | Generate the JavaScript snippet for live reload.
--
-- When injected into an HTML page, this script opens a WebSocket
-- connection to the live reload server and reloads the page whenever
-- a @\"reload\"@ message is received.
--
-- @since 0.19.2
liveReloadScript :: Int -> Text.Text
liveReloadScript port =
  Text.pack $
    "<script>"
      ++ "(function(){"
      ++ "var ws=new WebSocket('ws://localhost:" ++ show port ++ "');"
      ++ "ws.onmessage=function(e){if(e.data==='reload')location.reload();};"
      ++ "ws.onclose=function(){setTimeout(function(){"
      ++ "var r=new WebSocket('ws://localhost:" ++ show port ++ "');"
      ++ "r.onmessage=ws.onmessage;r.onclose=ws.onclose;"
      ++ "},1000);};"
      ++ "}());"
      ++ "</script>"

-- | Generate a JavaScript error overlay script.
--
-- Injects a styled error overlay into the page body to display
-- compilation errors directly in the browser during development.
--
-- @since 0.19.2
errorOverlayScript :: String -> Text.Text
errorOverlayScript errorMsg =
  Text.pack $
    "<script>"
      ++ "(function(){"
      ++ "var d=document.createElement('div');"
      ++ "d.style.cssText='position:fixed;top:0;left:0;right:0;bottom:0;"
      ++ "background:rgba(0,0,0,0.85);color:#ff6b6b;font-family:monospace;"
      ++ "font-size:14px;padding:40px;overflow:auto;z-index:999999;white-space:pre-wrap;';"
      ++ "d.textContent=" ++ jsStringLiteral errorMsg ++ ";"
      ++ "document.body.appendChild(d);"
      ++ "}());"
      ++ "</script>"

-- INTERNAL

-- | Run the WebSocket server loop.
runServer :: LiveReloadServer -> IO ()
runServer server =
  Exception.handle handleServerError $
    WS.runServer "0.0.0.0" (_lrsPort server) (handlePendingConnection server)
  where
    handleServerError :: IOException -> IO ()
    handleServerError _ = pure ()

-- | Accept a pending WebSocket connection and add it to the client list.
handlePendingConnection :: LiveReloadServer -> WS.PendingConnection -> IO ()
handlePendingConnection server pending = do
  conn <- WS.acceptRequest pending
  addClient server conn
  keepAlive conn

-- | Add a client connection to the server's client list.
addClient :: LiveReloadServer -> WS.Connection -> IO ()
addClient server conn = do
  clients <- MVar.takeMVar (_lrsClients server)
  MVar.putMVar (_lrsClients server) (conn : clients)

-- | Keep a WebSocket connection alive by reading messages until closed.
keepAlive :: WS.Connection -> IO ()
keepAlive conn =
  Exception.handle handleClose receiveLoop
  where
    receiveLoop = do
      _ <- WS.receiveDataMessage conn
      receiveLoop

    handleClose :: WS.ConnectionException -> IO ()
    handleClose _ = pure ()

-- | Broadcast reload message to all clients, returning only alive ones.
broadcastReload :: [WS.Connection] -> IO [WS.Connection]
broadcastReload = go []
  where
    go alive [] = pure alive
    go alive (conn : rest) = do
      success <- safeSendText conn "reload"
      if success
        then go (conn : alive) rest
        else go alive rest

-- | Send text to a WebSocket connection, returning False on failure.
safeSendText :: WS.Connection -> LBS8.ByteString -> IO Bool
safeSendText conn msg =
  (WS.sendTextData conn msg >> pure True)
    `Exception.catch` handleSendError
  where
    handleSendError :: WS.ConnectionException -> IO Bool
    handleSendError _ = pure False

-- | Safely close a WebSocket connection, ignoring errors.
safeClose :: WS.Connection -> IO ()
safeClose conn =
  WS.sendClose conn ("" :: LBS8.ByteString)
    `Exception.catch` handleCloseError
  where
    handleCloseError :: WS.ConnectionException -> IO ()
    handleCloseError _ = pure ()

-- | Escape a Haskell string into a JavaScript string literal.
jsStringLiteral :: String -> String
jsStringLiteral s = "'" ++ concatMap escapeChar s ++ "'"
  where
    escapeChar '\'' = "\\'"
    escapeChar '\\' = "\\\\"
    escapeChar '\n' = "\\n"
    escapeChar '\r' = "\\r"
    escapeChar '<' = "\\x3c"
    escapeChar c = [c]
