{-# LANGUAGE OverloadedStrings #-}

-- | Unit.Generate.JavaScript.ESMGenTest - Tests for ESM code generation
--
-- This module provides unit tests for the pure functions in
-- "Generate.JavaScript.ESM". All tested functions are pure and can be
-- exercised in isolation without running the full compiler pipeline.
--
-- == Test Coverage
--
-- * moduleComment: exact Builder output for canonical module names
-- * canonicalToFilename: flat filename from canonical module name
-- * canonicalToPathBs: quoted path ByteString from canonical module name
-- * isExternal: cross-module vs same-module global classification
-- * isInternalNode: Cycle/Manager nodes excluded from exports
-- * buildExportItems: empty map yields empty list; non-empty yields ExportLocals
-- * buildImportItems: runtime import is always first
-- * renderModule: Dev and Prod modes produce correct output
-- * varToConst: Var statements converted to Const at module scope
-- * flattenCycleToModule: Block of Var statements flattened to ModuleStmt items
-- * groupDepsByModule: globals grouped by home module
-- * nodeDeps: dependency sets extracted correctly per node kind
-- * managerEffectDeps: correct dep sets for Cmd/Sub/Fx managers
--
-- @since 0.20.0
module Unit.Generate.JavaScript.ESMGenTest
  ( tests,
  )
where

import qualified AST.Optimized as Opt
import qualified Canopy.Data.Index as Index
import qualified Canopy.Data.Name as Name
import qualified Canopy.ModuleName as ModuleName
import qualified Data.ByteString.Builder as BB
import qualified Data.ByteString.Lazy as LBS
import qualified Data.Map.Strict as Map
import qualified Data.Set as Set
import qualified Generate.JavaScript.Builder as JS
import qualified Generate.JavaScript.ESM as ESM
import qualified Generate.JavaScript.Name as JsName
import qualified Generate.JavaScript.StringPool as StringPool
import qualified Generate.Mode as Mode
import Test.Tasty
import Test.Tasty.HUnit

-- ---------------------------------------------------------------------------
-- Test root
-- ---------------------------------------------------------------------------

-- | Root test tree for Generate.JavaScript.ESM.
tests :: TestTree
tests =
  testGroup
    "Generate.JavaScript.ESM Tests"
    [ moduleCommentTests,
      canonicalToFilenameTests,
      canonicalToPathBsTests,
      isExternalTests,
      isInternalNodeTests,
      buildExportItemsTests,
      buildImportItemsTests,
      renderModuleTests,
      varToConstTests,
      flattenCycleToModuleTests,
      groupDepsByModuleTests,
      nodeDepsTests,
      managerEffectDepsTests
    ]

-- ---------------------------------------------------------------------------
-- Fixtures
-- ---------------------------------------------------------------------------

-- | Dev mode with no optional flags enabled.
devMode :: Mode.Mode
devMode = Mode.Dev Nothing False False False Set.empty False

-- | Prod mode with empty field map, pool, and rename map.
prodMode :: Mode.Mode
prodMode = Mode.Prod Map.empty False False False StringPool.emptyPool Set.empty Map.empty

-- | Canonical module name for elm/core Basics.
basicsHome :: ModuleName.Canonical
basicsHome = ModuleName.basics

-- | Canonical module name for elm/core List.
listHome :: ModuleName.Canonical
listHome = ModuleName.list

-- ---------------------------------------------------------------------------
-- moduleComment
-- ---------------------------------------------------------------------------

-- | Tests for 'ESM.moduleComment'.
moduleCommentTests :: TestTree
moduleCommentTests =
  testGroup
    "moduleComment"
    [ testCase "basics module comment exact expected string" $
        BB.toLazyByteString (ESM.moduleComment basicsHome)
          @?= "// elm.core.Basics.js\n// Auto-generated by the Canopy compiler. Do not edit.\n\n",
      testCase "list module comment exact expected string" $
        BB.toLazyByteString (ESM.moduleComment listHome)
          @?= "// elm.core.List.js\n// Auto-generated by the Canopy compiler. Do not edit.\n\n",
      testCase "module comment starts with //" $
        LBS.isPrefixOf "//" (BB.toLazyByteString (ESM.moduleComment basicsHome))
          @?= True,
      testCase "module comment ends with double newline" $
        LBS.isSuffixOf "\n\n" (BB.toLazyByteString (ESM.moduleComment basicsHome))
          @?= True
    ]

-- ---------------------------------------------------------------------------
-- canonicalToFilename
-- ---------------------------------------------------------------------------

-- | Tests for 'ESM.canonicalToFilename'.
canonicalToFilenameTests :: TestTree
canonicalToFilenameTests =
  testGroup
    "canonicalToFilename"
    [ testCase "basics module produces elm.core.Basics.js" $
        BB.toLazyByteString (ESM.canonicalToFilename basicsHome)
          @?= "elm.core.Basics.js",
      testCase "list module produces elm.core.List.js" $
        BB.toLazyByteString (ESM.canonicalToFilename listHome)
          @?= "elm.core.List.js",
      testCase "filename ends with .js extension" $
        LBS.isSuffixOf ".js" (BB.toLazyByteString (ESM.canonicalToFilename basicsHome))
          @?= True
    ]

-- ---------------------------------------------------------------------------
-- canonicalToPathBs
-- ---------------------------------------------------------------------------

-- | Tests for 'ESM.canonicalToPathBs'.
canonicalToPathBsTests :: TestTree
canonicalToPathBsTests =
  testGroup
    "canonicalToPathBs"
    [ testCase "basics module path is ./elm.core.Basics.js in single quotes" $
        ESM.canonicalToPathBs basicsHome
          @?= "'./elm.core.Basics.js'",
      testCase "list module path is ./elm.core.List.js in single quotes" $
        ESM.canonicalToPathBs listHome
          @?= "'./elm.core.List.js'",
      testCase "path starts with single quote" $
        LBS.isPrefixOf "'" (LBS.fromStrict (ESM.canonicalToPathBs basicsHome))
          @?= True,
      testCase "path ends with single quote" $
        LBS.isSuffixOf "'" (LBS.fromStrict (ESM.canonicalToPathBs basicsHome))
          @?= True
    ]

-- ---------------------------------------------------------------------------
-- isExternal
-- ---------------------------------------------------------------------------

-- | Tests for 'ESM.isExternal'.
isExternalTests :: TestTree
isExternalTests =
  testGroup
    "isExternal"
    [ testCase "global from same home is not external" $
        ESM.isExternal basicsHome (Opt.Global basicsHome (Name.fromChars "add"))
          @?= False,
      testCase "global from different home is external" $
        ESM.isExternal basicsHome (Opt.Global listHome (Name.fromChars "map"))
          @?= True,
      testCase "global from list home is not external when list is home" $
        ESM.isExternal listHome (Opt.Global listHome (Name.fromChars "filter"))
          @?= False
    ]

-- ---------------------------------------------------------------------------
-- isInternalNode
-- ---------------------------------------------------------------------------

-- | Tests for 'ESM.isInternalNode'.
isInternalNodeTests :: TestTree
isInternalNodeTests =
  testGroup
    "isInternalNode"
    [ testCase "Cycle node is internal" $
        ESM.isInternalNode (Opt.Cycle [] [] [] Set.empty) @?= True,
      testCase "Manager Cmd node is internal" $
        ESM.isInternalNode (Opt.Manager Opt.Cmd) @?= True,
      testCase "Manager Sub node is internal" $
        ESM.isInternalNode (Opt.Manager Opt.Sub) @?= True,
      testCase "Manager Fx node is internal" $
        ESM.isInternalNode (Opt.Manager Opt.Fx) @?= True,
      testCase "Enum node is not internal" $
        ESM.isInternalNode (Opt.Enum Index.first) @?= False,
      testCase "Box node is not internal" $
        ESM.isInternalNode Opt.Box @?= False,
      testCase "Link node is not internal" $
        ESM.isInternalNode (Opt.Link (Opt.Global basicsHome (Name.fromChars "id"))) @?= False
    ]

-- ---------------------------------------------------------------------------
-- buildExportItems
-- ---------------------------------------------------------------------------

-- | Tests for 'ESM.buildExportItems'.
buildExportItemsTests :: TestTree
buildExportItemsTests =
  testGroup
    "buildExportItems"
    [ testCase "empty entries produce empty list" $
        length (ESM.buildExportItems Map.empty) @?= 0,
      testCase "entries with only Cycle nodes produce empty list" $
        let entries =
              Map.singleton
                (Name.fromChars "cycle")
                (Opt.Global basicsHome (Name.fromChars "cycle"), Opt.Cycle [] [] [] Set.empty)
        in length (ESM.buildExportItems entries) @?= 0,
      testCase "entries with only Manager nodes produce empty list" $
        let entries =
              Map.singleton
                (Name.fromChars "mgr")
                (Opt.Global basicsHome (Name.fromChars "mgr"), Opt.Manager Opt.Cmd)
        in length (ESM.buildExportItems entries) @?= 0,
      testCase "Enum entry produces exactly one item" $
        let global = Opt.Global basicsHome (Name.fromChars "myEnum")
            entries =
              Map.singleton
                (Name.fromChars "myEnum")
                (global, Opt.Enum Index.first)
        in length (ESM.buildExportItems entries) @?= 1,
      testCase "exportable entry produces ExportLocals item" $
        let global = Opt.Global basicsHome (Name.fromChars "myEnum")
            entries =
              Map.singleton
                (Name.fromChars "myEnum")
                (global, Opt.Enum Index.first)
        in case ESM.buildExportItems entries of
             [JS.ExportLocals _] -> pure ()
             other -> assertFailure ("Expected [ExportLocals _], got: " ++ show other),
      testCase "Box entry produces exactly one item" $
        let global = Opt.Global basicsHome (Name.fromChars "boxed")
            entries =
              Map.singleton
                (Name.fromChars "boxed")
                (global, Opt.Box)
        in length (ESM.buildExportItems entries) @?= 1
    ]

-- ---------------------------------------------------------------------------
-- buildImportItems
-- ---------------------------------------------------------------------------

-- | Tests for 'ESM.buildImportItems'.
--
-- The first item must always be the bare runtime import.
buildImportItemsTests :: TestTree
buildImportItemsTests =
  testGroup
    "buildImportItems"
    [ testCase "first import is always the bare runtime import" $
        let items = ESM.buildImportItems Set.empty basicsHome Map.empty
        in case items of
             (JS.ImportBare path : _) ->
               path @?= "'./canopy-runtime.js'"
             _ -> assertFailure "Expected first item to be ImportBare './canopy-runtime.js'",
      testCase "no external deps yields exactly one item (runtime import)" $
        let items = ESM.buildImportItems Set.empty basicsHome Map.empty
        in length items @?= 1,
      testCase "external dep in reachable set adds a cross-module import" $
        let listGlobal = Opt.Global listHome (Name.fromChars "map")
            reachable = Set.singleton listGlobal
            entries =
              Map.singleton
                (Name.fromChars "add")
                ( Opt.Global basicsHome (Name.fromChars "add"),
                  Opt.Define (Opt.Int 0) (Set.singleton listGlobal)
                )
            items = ESM.buildImportItems reachable basicsHome entries
        in length items @?= 2,
      testCase "external dep yields ImportNamed as second item" $
        let listGlobal = Opt.Global listHome (Name.fromChars "map")
            reachable = Set.singleton listGlobal
            entries =
              Map.singleton
                (Name.fromChars "add")
                ( Opt.Global basicsHome (Name.fromChars "add"),
                  Opt.Define (Opt.Int 0) (Set.singleton listGlobal)
                )
            items = ESM.buildImportItems reachable basicsHome entries
        in case items of
             [_, JS.ImportNamed _ _] -> pure ()
             _ -> assertFailure "Expected [ImportBare, ImportNamed _]"
    ]

-- ---------------------------------------------------------------------------
-- renderModule
-- ---------------------------------------------------------------------------

-- | Tests for 'ESM.renderModule'.
--
-- Both dev and prod modes must emit RawJS content verbatim.
renderModuleTests :: TestTree
renderModuleTests =
  testGroup
    "renderModule"
    [ testCase "dev mode renders RawJS content verbatim" $
        BB.toLazyByteString (ESM.renderModule devMode [JS.RawJS "// marker\n"])
          @?= "// marker\n",
      testCase "prod mode renders RawJS content verbatim" $
        BB.toLazyByteString (ESM.renderModule prodMode [JS.RawJS "// marker\n"])
          @?= "// marker\n",
      testCase "dev mode with empty items produces empty output" $
        BB.toLazyByteString (ESM.renderModule devMode [])
          @?= "",
      testCase "prod mode with empty items produces empty output" $
        BB.toLazyByteString (ESM.renderModule prodMode [])
          @?= "",
      testCase "multiple RawJS items are concatenated in order" $
        BB.toLazyByteString (ESM.renderModule devMode [JS.RawJS "a", JS.RawJS "b"])
          @?= "ab"
    ]

-- ---------------------------------------------------------------------------
-- varToConst
-- ---------------------------------------------------------------------------

-- | Tests for 'ESM.varToConst'.
varToConstTests :: TestTree
varToConstTests =
  testGroup
    "varToConst"
    [ testCase "Var becomes Const" $
        let name = JsName.fromBuilder "x"
        in case ESM.varToConst (JS.Var name (JS.Int 42)) of
             JS.Const _ _ -> pure ()
             other -> assertFailure ("Expected Const, got: " ++ show other),
      testCase "Block of Var becomes Block of Const" $
        let name = JsName.fromBuilder "y"
        in case ESM.varToConst (JS.Block [JS.Var name (JS.Bool True)]) of
             JS.Block [JS.Const _ _] -> pure ()
             other -> assertFailure ("Expected Block [Const _], got: " ++ show other),
      testCase "Return passes through as Return" $
        case ESM.varToConst (JS.Return (JS.Int 0)) of
          JS.Return _ -> pure ()
          other -> assertFailure ("Expected Return, got: " ++ show other),
      testCase "EmptyStmt passes through as EmptyStmt" $
        case ESM.varToConst JS.EmptyStmt of
          JS.EmptyStmt -> pure ()
          other -> assertFailure ("Expected EmptyStmt, got: " ++ show other),
      testCase "nested Block of Var converted at all levels" $
        let name = JsName.fromBuilder "z"
        in case ESM.varToConst (JS.Block [JS.Block [JS.Var name (JS.Int 1)]]) of
             JS.Block [JS.Block [JS.Const _ _]] -> pure ()
             other -> assertFailure ("Expected Block [Block [Const _]], got: " ++ show other)
    ]

-- ---------------------------------------------------------------------------
-- flattenCycleToModule
-- ---------------------------------------------------------------------------

-- | Tests for 'ESM.flattenCycleToModule'.
flattenCycleToModuleTests :: TestTree
flattenCycleToModuleTests =
  testGroup
    "flattenCycleToModule"
    [ testCase "Var at top level becomes one ModuleStmt Const" $
        let name = JsName.fromBuilder "c"
        in case ESM.flattenCycleToModule (JS.Var name (JS.Int 3)) of
             [JS.ModuleStmt (JS.Const _ _)] -> pure ()
             other -> assertFailure ("Expected [ModuleStmt (Const _)], got: " ++ show other),
      testCase "Block of two Var statements yields exactly two items" $
        let name1 = JsName.fromBuilder "a"
            name2 = JsName.fromBuilder "b"
            block = JS.Block [JS.Var name1 (JS.Int 1), JS.Var name2 (JS.Int 2)]
        in length (ESM.flattenCycleToModule block) @?= 2,
      testCase "Block of two Var statements yields all ModuleStmt Const items" $
        let name1 = JsName.fromBuilder "a"
            name2 = JsName.fromBuilder "b"
            block = JS.Block [JS.Var name1 (JS.Int 1), JS.Var name2 (JS.Int 2)]
        in case ESM.flattenCycleToModule block of
             [JS.ModuleStmt (JS.Const _ _), JS.ModuleStmt (JS.Const _ _)] -> pure ()
             other -> assertFailure ("Expected two ModuleStmt Const, got: " ++ show other),
      testCase "non-Block non-Var statement becomes single ModuleStmt" $
        case ESM.flattenCycleToModule (JS.Return (JS.Int 0)) of
          [JS.ModuleStmt _] -> pure ()
          other -> assertFailure ("Expected [ModuleStmt _], got: " ++ show other),
      testCase "empty Block produces empty list" $
        length (ESM.flattenCycleToModule (JS.Block [])) @?= 0
    ]

-- ---------------------------------------------------------------------------
-- groupDepsByModule
-- ---------------------------------------------------------------------------

-- | Tests for 'ESM.groupDepsByModule'.
groupDepsByModuleTests :: TestTree
groupDepsByModuleTests =
  testGroup
    "groupDepsByModule"
    [ testCase "empty set produces empty map" $
        ESM.groupDepsByModule Set.empty @?= Map.empty,
      testCase "single global forms one entry under its home" $
        let global = Opt.Global basicsHome (Name.fromChars "add")
        in Map.size (ESM.groupDepsByModule (Set.singleton global)) @?= 1,
      testCase "two globals from same home form one group of size two" $
        let g1 = Opt.Global basicsHome (Name.fromChars "add")
            g2 = Opt.Global basicsHome (Name.fromChars "sub")
            result = ESM.groupDepsByModule (Set.fromList [g1, g2])
        in fmap Set.size (Map.lookup basicsHome result) @?= Just 2,
      testCase "globals from two distinct homes produce two map entries" $
        let g1 = Opt.Global basicsHome (Name.fromChars "add")
            g2 = Opt.Global listHome (Name.fromChars "map")
        in Map.size (ESM.groupDepsByModule (Set.fromList [g1, g2])) @?= 2,
      testCase "three globals: two from basics, one from list yields correct groups" $
        let g1 = Opt.Global basicsHome (Name.fromChars "add")
            g2 = Opt.Global basicsHome (Name.fromChars "sub")
            g3 = Opt.Global listHome (Name.fromChars "map")
            result = ESM.groupDepsByModule (Set.fromList [g1, g2, g3])
        in do
             Map.size result @?= 2
             fmap Set.size (Map.lookup basicsHome result) @?= Just 2
             fmap Set.size (Map.lookup listHome result) @?= Just 1
    ]

-- ---------------------------------------------------------------------------
-- nodeDeps
-- ---------------------------------------------------------------------------

-- | Tests for 'ESM.nodeDeps'.
nodeDepsTests :: TestTree
nodeDepsTests =
  testGroup
    "nodeDeps"
    [ testCase "Ctor node has empty deps" $
        ESM.nodeDeps (Opt.Ctor Index.first 2) @?= Set.empty,
      testCase "Enum node has empty deps" $
        ESM.nodeDeps (Opt.Enum Index.first) @?= Set.empty,
      testCase "Box node has empty deps" $
        ESM.nodeDeps Opt.Box @?= Set.empty,
      testCase "Manager Cmd node has empty deps" $
        ESM.nodeDeps (Opt.Manager Opt.Cmd) @?= Set.empty,
      testCase "AbilityDict node has empty deps" $
        ESM.nodeDeps (Opt.AbilityDict [Name.fromChars "MyAbility"]) @?= Set.empty,
      testCase "Link node has exactly one dep on the linked global" $
        let target = Opt.Global basicsHome (Name.fromChars "add")
        in ESM.nodeDeps (Opt.Link target) @?= Set.singleton target,
      testCase "Define node returns its dep set" $
        let dep = Opt.Global listHome (Name.fromChars "map")
            deps = Set.singleton dep
        in ESM.nodeDeps (Opt.Define (Opt.Int 0) deps) @?= deps,
      testCase "DefineTailFunc node returns its dep set" $
        let dep = Opt.Global basicsHome (Name.fromChars "sub")
            deps = Set.singleton dep
        in ESM.nodeDeps (Opt.DefineTailFunc [] (Opt.Int 0) deps) @?= deps,
      testCase "Kernel node returns its dep set" $
        let dep = Opt.Global basicsHome (Name.fromChars "eq")
            deps = Set.singleton dep
        in ESM.nodeDeps (Opt.Kernel [] deps) @?= deps,
      testCase "Cycle node returns its dep set" $
        let dep = Opt.Global basicsHome (Name.fromChars "helper")
            deps = Set.singleton dep
        in ESM.nodeDeps (Opt.Cycle [] [] [] deps) @?= deps,
      testCase "PortIncoming node returns its dep set" $
        let dep = Opt.Global basicsHome (Name.fromChars "decoder")
            deps = Set.singleton dep
        in ESM.nodeDeps (Opt.PortIncoming (Opt.Int 0) deps) @?= deps,
      testCase "PortOutgoing node returns its dep set" $
        let dep = Opt.Global basicsHome (Name.fromChars "encoder")
            deps = Set.singleton dep
        in ESM.nodeDeps (Opt.PortOutgoing (Opt.Int 0) deps) @?= deps,
      testCase "ImplDict node returns its dep set" $
        let dep = Opt.Global basicsHome (Name.fromChars "fn")
            deps = Set.singleton dep
        in ESM.nodeDeps (Opt.ImplDict (Name.fromChars "Ab") Map.empty deps) @?= deps
    ]

-- ---------------------------------------------------------------------------
-- managerEffectDeps
-- ---------------------------------------------------------------------------

-- | Tests for 'ESM.managerEffectDeps'.
--
-- Verifies the exact name sets for each 'Opt.EffectsType'.
managerEffectDepsTests :: TestTree
managerEffectDepsTests =
  testGroup
    "managerEffectDeps"
    [ testCase "Cmd manager has exactly init, onEffects, onSelfMsg, cmdMap" $
        ESM.managerEffectDeps Opt.Cmd
          @?= Set.fromList
            (map Name.fromChars ["init", "onEffects", "onSelfMsg", "cmdMap"]),
      testCase "Sub manager has exactly init, onEffects, onSelfMsg, subMap" $
        ESM.managerEffectDeps Opt.Sub
          @?= Set.fromList
            (map Name.fromChars ["init", "onEffects", "onSelfMsg", "subMap"]),
      testCase "Fx manager has exactly init, onEffects, onSelfMsg, cmdMap, subMap" $
        ESM.managerEffectDeps Opt.Fx
          @?= Set.fromList
            (map Name.fromChars ["init", "onEffects", "onSelfMsg", "cmdMap", "subMap"]),
      testCase "Cmd deps set has cardinality 4" $
        Set.size (ESM.managerEffectDeps Opt.Cmd) @?= 4,
      testCase "Sub deps set has cardinality 4" $
        Set.size (ESM.managerEffectDeps Opt.Sub) @?= 4,
      testCase "Fx deps set has cardinality 5" $
        Set.size (ESM.managerEffectDeps Opt.Fx) @?= 5,
      testCase "Cmd contains cmdMap but not subMap" $
        let deps = ESM.managerEffectDeps Opt.Cmd
        in ( Set.member (Name.fromChars "cmdMap") deps,
             Set.member (Name.fromChars "subMap") deps
           )
             @?= (True, False),
      testCase "Sub contains subMap but not cmdMap" $
        let deps = ESM.managerEffectDeps Opt.Sub
        in ( Set.member (Name.fromChars "subMap") deps,
             Set.member (Name.fromChars "cmdMap") deps
           )
             @?= (True, False),
      testCase "Fx contains both cmdMap and subMap" $
        let deps = ESM.managerEffectDeps Opt.Fx
        in ( Set.member (Name.fromChars "cmdMap") deps,
             Set.member (Name.fromChars "subMap") deps
           )
             @?= (True, True)
    ]
