module TestUnit exposing (main)

import Html exposing (Html, text)
import Capability exposing (UserActivated(..), CapabilityError)

foreign import javascript "external/audio.js" as AudioFFI

type AudioResult err val
    = Ok val
    | Err err

type AudioContext = AudioContext

closeAudioContext : AudioContext -> AudioResult CapabilityError ()
closeAudioContext audioContext =
    AudioFFI.closeAudioContext audioContext

main : Html Never
main =
    text "Test"
