// Auto-generated test runner
// Generated by canopy test

// Setup mock DOM for Node.js environment
let capturedOutput = '';

function createMockElement(tag) {
  const children = [];
  return {
    tagName: tag,
    style: {},
    children: children,
    textContent: '',
    appendChild: function(child) {
      children.push(child);
      return child;
    },
    removeChild: function(child) {
      const idx = children.indexOf(child);
      if (idx >= 0) children.splice(idx, 1);
      return child;
    },
    replaceChild: function(newChild, oldChild) {
      const idx = children.indexOf(oldChild);
      if (idx >= 0) children[idx] = newChild;
      return oldChild;
    },
    insertBefore: function(newNode, refNode) {
      const idx = children.indexOf(refNode);
      if (idx >= 0) children.splice(idx, 0, newNode);
      else children.push(newNode);
      return newNode;
    },
    addEventListener: function() {},
    removeEventListener: function() {},
    getTextContent: function() {
      return extractText(this);
    }
  };
}

function extractText(node) {
  if (!node) return '';
  if (typeof node === 'string') return node;
  if (node.textContent) return node.textContent;
  if (node.children && node.children.length > 0) {
    return node.children.map(extractText).join('');
  }
  return '';
}

const bodyElement = createMockElement('body');
const rootElement = createMockElement('div');
rootElement.parentNode = bodyElement;
bodyElement.children.push(rootElement);

global.window = global;
global.document = {
  body: bodyElement,
  createElement: createMockElement,
  createTextNode: (text) => ({ textContent: text }),
  createComment: (text) => ({ textContent: text }),
  createDocumentFragment: () => createMockElement('fragment'),
  head: createMockElement('head'),
  getElementById: () => rootElement,
  querySelector: () => null,
  querySelectorAll: () => [],
  addEventListener: function() {},
  removeEventListener: function() {}
};
global.requestAnimationFrame = (cb) => setTimeout(cb, 16);
global.cancelAnimationFrame = (id) => clearTimeout(id);

// Load performance API for timing
const { performance } = require('perf_hooks');
global.performance = performance;

// Load compiled tests
require('/home/quinten/fh/canopy/examples/audio-ffi/.canopy-test/TestMain.js');

// Find the Canopy app
const Canopy = global.Elm || global.Canopy;
if (!Canopy) {
  console.error('Error: No Canopy export found');
  process.exit(1);
}

// Find TestMain module
const TestMain = Canopy.TestMain;
if (!TestMain) {
  console.error('Error: TestMain module not found');
  console.error('Available modules:', Object.keys(Canopy));
  process.exit(1);
}

// Initialize and run
try {
  const app = TestMain.init({ node: rootElement });

  // Wait for rendering and extract output
  setTimeout(() => {
    // The VirtualDom replaces rootElement, so extract from bodyElement
    const renderedNode = bodyElement.children[0];
    const output = extractText(renderedNode);
    console.log(output);
    
    // Parse output to determine exit code
    const hasFailed = output.includes('FAIL') || output.includes('failed');
    process.exit(hasFailed ? 1 : 0);
  }, 5000);
} catch (e) {
  console.error('Test execution error:', e.message);
  console.error(e.stack);
  process.exit(1);
}
