{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE LambdaCase #-}

-- | JavaScript Kernel Code Generator
--
-- Generates JavaScript runtime code that implements the FFI bindings
-- for Canopy modules. Creates kernel-style JavaScript that integrates
-- with the Canopy runtime.
--
-- @since 0.20.0
module WebIDL.Codegen.JavaScript
  ( -- * Module rendering
    renderModule
  , renderFunction
  , renderGetter
  , renderSetter
  , renderConstructor

    -- * Type conversion
  , renderToJs
  , renderFromJs
  ) where

import Data.Text (Text)
import qualified Data.Text as Text

import WebIDL.Config
import WebIDL.Transform


-- | Render a complete JavaScript kernel module
renderModule :: Config -> CanopyModule -> Text
renderModule config canopyMod = Text.unlines
  [ renderModuleHeader config canopyMod
  , ""
  , renderHelpers
  , ""
  , renderFunctions config canopyMod
  , ""
  , renderModuleExports canopyMod
  ]


-- | Render module header with IIFE wrapper
renderModuleHeader :: Config -> CanopyModule -> Text
renderModuleHeader _config canopyMod = Text.unlines
  [ "/*"
  , " * Generated by canopy-webidl"
  , " * Module: " <> cmName canopyMod
  , " * DO NOT EDIT - This file is auto-generated"
  , " */"
  , ""
  , "(function(scope) {"
  , "'use strict';"
  ]


-- | Render helper functions for type conversion
renderHelpers :: Text
renderHelpers = Text.unlines
  [ "// Type conversion helpers"
  , ""
  , "function _Maybe_Just(value) {"
  , "    return { $: 'Just', a: value };"
  , "}"
  , ""
  , "var _Maybe_Nothing = { $: 'Nothing' };"
  , ""
  , "function _toMaybe(value) {"
  , "    return value == null ? _Maybe_Nothing : _Maybe_Just(value);"
  , "}"
  , ""
  , "function _fromMaybe(maybe, defaultValue) {"
  , "    return maybe.$ === 'Just' ? maybe.a : defaultValue;"
  , "}"
  , ""
  , "function _Result_Ok(value) {"
  , "    return { $: 'Ok', a: value };"
  , "}"
  , ""
  , "function _Result_Err(error) {"
  , "    return { $: 'Err', a: error };"
  , "}"
  , ""
  , "function _Task_succeed(value) {"
  , "    return {"
  , "        $: '_Task_succeed',"
  , "        a: value"
  , "    };"
  , "}"
  , ""
  , "function _Task_fail(error) {"
  , "    return {"
  , "        $: '_Task_fail',"
  , "        a: error"
  , "    };"
  , "}"
  , ""
  , "function _Task_fromPromise(promise) {"
  , "    return {"
  , "        $: '_Task_binding',"
  , "        a: function(callback) {"
  , "            promise.then("
  , "                function(value) { callback(_Task_succeed(value)); },"
  , "                function(error) { callback(_Task_fail(error)); }"
  , "            );"
  , "        }"
  , "    };"
  , "}"
  , ""
  , "function _List_fromArray(array) {"
  , "    var result = { $: '[]' };"
  , "    for (var i = array.length - 1; i >= 0; i--) {"
  , "        result = { $: '::', a: array[i], b: result };"
  , "    }"
  , "    return result;"
  , "}"
  , ""
  , "function _List_toArray(list) {"
  , "    var result = [];"
  , "    while (list.$ === '::') {"
  , "        result.push(list.a);"
  , "        list = list.b;"
  , "    }"
  , "    return result;"
  , "}"
  ]


-- | Render all function implementations
renderFunctions :: Config -> CanopyModule -> Text
renderFunctions config canopyMod =
  Text.unlines (map (renderFunctionImpl config) (cmFunctions canopyMod))


-- | Render a single function implementation
renderFunctionImpl :: Config -> CanopyFunction -> Text
renderFunctionImpl _config func
  | isGetter func = renderGetter func
  | isSetter func = renderSetter func
  | isConstructor func = renderConstructor func
  | otherwise = renderFunction func


-- | Check if function is a getter
isGetter :: CanopyFunction -> Bool
isGetter func =
  not (cfIsStatic func)
    && length (cfParams func) == 1
    && not (Text.isPrefixOf "set" (cfName func))


-- | Check if function is a setter
isSetter :: CanopyFunction -> Bool
isSetter func =
  not (cfIsStatic func)
    && length (cfParams func) == 2
    && Text.isPrefixOf "set" (cfName func)


-- | Check if function is a constructor
isConstructor :: CanopyFunction -> Bool
isConstructor func =
  Text.isPrefixOf "new" (cfName func) && cfIsStatic func


-- | Render a regular function
renderFunction :: CanopyFunction -> Text
renderFunction func = Text.unlines
  [ "var " <> jsFuncName <> " = " <> renderCurriedFunction params body <> ";"
  , ""
  ]
  where
    jsFuncName = toJsFunctionName func
    params = map fst (cfParams func)
    body = renderMethodCall func


-- | Render a property getter
renderGetter :: CanopyFunction -> Text
renderGetter func = Text.unlines
  [ "var " <> jsFuncName <> " = function(self) {"
  , "    return " <> wrapReturn (cfReturn func) getter <> ";"
  , "};"
  , ""
  ]
  where
    jsFuncName = toJsFunctionName func
    getter = "self." <> cfJsName func


-- | Render a property setter
renderSetter :: CanopyFunction -> Text
renderSetter func = Text.unlines
  [ "var " <> jsFuncName <> " = F2(function(self, value) {"
  , "    self." <> attrName <> " = " <> unwrapParam valueType "value" <> ";"
  , "    return self;"
  , "});"
  , ""
  ]
  where
    jsFuncName = toJsFunctionName func
    attrName = Text.drop 3 (cfJsName func)  -- Remove "set" prefix
    valueType = case cfParams func of
      [_, (_, vt)] -> vt
      _ -> CTValue  -- Setter always has 2 params (validated by isSetter)


-- | Render a constructor
renderConstructor :: CanopyFunction -> Text
renderConstructor func = Text.unlines
  [ "var " <> jsFuncName <> " = " <> renderCurriedFunction params body <> ";"
  , ""
  ]
  where
    jsFuncName = toJsFunctionName func
    params = map fst (cfParams func)
    className = maybe (cfJsName func) id (cfJsTarget func)
    args = Text.intercalate ", " (zipWith unwrapArg (cfParams func) params)
    body = "new " <> className <> "(" <> args <> ")"

    unwrapArg (_, ty) name = unwrapParam ty name


-- | Render a curried function
renderCurriedFunction :: [Text] -> Text -> Text
renderCurriedFunction [] body = "function() { return " <> body <> "; }"
renderCurriedFunction [p] body = "function(" <> p <> ") { return " <> body <> "; }"
renderCurriedFunction params body =
  "F" <> Text.pack (show (length params)) <> "(function(" <> paramList <> ") { return " <> body <> "; })"
  where
    paramList = Text.intercalate ", " params


-- | Render method call
renderMethodCall :: CanopyFunction -> Text
renderMethodCall func =
  case cfJsTarget func of
    Nothing -> renderFunctionCall func
    Just target ->
      if cfIsStatic func
        then renderStaticCall target func
        else renderInstanceCall func


-- | Render static method call
renderStaticCall :: Text -> CanopyFunction -> Text
renderStaticCall target func =
  wrapReturn (cfReturn func) call
  where
    args = Text.intercalate ", " (zipWith renderArg (cfParams func) (map fst (cfParams func)))
    call = target <> "." <> cfJsName func <> "(" <> args <> ")"
    renderArg (_, ty) name = unwrapParam ty name


-- | Render instance method call
renderInstanceCall :: CanopyFunction -> Text
renderInstanceCall func =
  wrapReturn (cfReturn func) call
  where
    (selfParam, otherParams) = case cfParams func of
      ((name, _):rest) -> (name, rest)
      [] -> ("", [])
    args = Text.intercalate ", " (zipWith renderArg otherParams (map fst otherParams))
    call = selfParam <> "." <> cfJsName func <> "(" <> args <> ")"
    renderArg (_, ty) name = unwrapParam ty name


-- | Render direct function call
renderFunctionCall :: CanopyFunction -> Text
renderFunctionCall func =
  wrapReturn (cfReturn func) call
  where
    args = Text.intercalate ", " (zipWith renderArg (cfParams func) (map fst (cfParams func)))
    call = cfJsName func <> "(" <> args <> ")"
    renderArg (_, ty) name = unwrapParam ty name


-- | Unwrap a Canopy value to JavaScript
unwrapParam :: CanopyType -> Text -> Text
unwrapParam ty name = case ty of
  CTMaybe _ -> "_fromMaybe(" <> name <> ", null)"
  CTList _ -> "_List_toArray(" <> name <> ")"
  _ -> name


-- | Wrap JavaScript value to Canopy
wrapReturn :: CanopyType -> Text -> Text
wrapReturn ty expr = case ty of
  CTMaybe _ -> "_toMaybe(" <> expr <> ")"
  CTList _ -> "_List_fromArray(" <> expr <> ")"
  CTTask _ _ -> "_Task_fromPromise(" <> expr <> ")"
  _ -> expr


-- | Convert to JavaScript function name
toJsFunctionName :: CanopyFunction -> Text
toJsFunctionName func =
  case cfJsTarget func of
    Nothing -> "_" <> cfJsName func
    Just target -> "_" <> target <> "_" <> cfJsName func


-- | Render module exports
renderModuleExports :: CanopyModule -> Text
renderModuleExports canopyMod = Text.unlines
  [ "// Module exports"
  , "scope['" <> cmName canopyMod <> "'] = {"
  , renderExportEntries (cmFunctions canopyMod)
  , "};"
  , ""
  , "})(this);"
  ]


-- | Render export entries
renderExportEntries :: [CanopyFunction] -> Text
renderExportEntries funcs =
  Text.intercalate ",\n" (map renderExport funcs)
  where
    renderExport func =
      "    " <> cfName func <> ": " <> toJsFunctionName func


-- | Render conversion to JavaScript
renderToJs :: CanopyType -> Text -> Text
renderToJs = unwrapParam


-- | Render conversion from JavaScript
renderFromJs :: CanopyType -> Text -> Text
renderFromJs = wrapReturn
