{-# LANGUAGE OverloadedStrings #-}

-- | FFI file transformation for ESM output.
--
-- Converts @.ffi.js@ files from IIFE-compatible format (where runtime globals
-- are in scope) into standalone ES modules that explicitly import runtime
-- symbols from @canopy-runtime.js@.
--
-- In IIFE mode, FFI bridge files like @external\/basics.js@ do
-- @var add = _Basics_add;@ and the runtime globals are in scope.
-- In ESM mode, each FFI file becomes its own module that must import
-- those symbols explicitly. It also creates a namespace object matching
-- the FFI alias (e.g., @BrowserFFI@) and registers it on @globalThis@
-- so consuming modules can reference @BrowserFFI.element(...)@.
--
-- @since 0.20.0
module Generate.JavaScript.ESM.FFI
  ( generateFFIModule,
    scanRuntimeRefs,
    scanRuntimeRefsFiltered,
  )
where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import Data.ByteString.Builder (Builder)
import qualified Data.ByteString.Builder as BB
import Data.Set (Set)
import qualified Data.Set as Set
import qualified Data.Text as Text
import qualified Data.Text.Encoding as Text
import qualified Generate.JavaScript.Builder as JS
import qualified Generate.JavaScript.FFI as FFI

-- | Known runtime symbol prefixes that indicate a reference to
-- the Canopy runtime. Used to scan FFI file content for symbols
-- that need to be imported from @canopy-runtime.js@.
runtimePrefixes :: [Text.Text]
runtimePrefixes =
  [ "_Utils_", "_List_", "_Basics_", "_Debug_",
    "_Scheduler_", "_Platform_", "_Process_",
    "_Json_", "_Array_"
  ]

-- | Known currying helper names from the runtime.
curryingHelpers :: [Text.Text]
curryingHelpers =
  ["F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9",
   "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "F"]

-- | Generate an ESM module from FFI file content.
--
-- Scans the FFI content for references to runtime globals and
-- currying helpers, prepends the necessary imports from
-- @canopy-runtime.js@. Extracts @\@name@ annotated functions and
-- internal @_@-prefixed declarations, then creates a namespace
-- object registered on @globalThis@ so consuming modules can
-- reference @AliasName.funcName(...)@.
--
-- @since 0.20.0
generateFFIModule :: Set Text.Text -> Text.Text -> String -> Builder
generateFFIModule runtimeWhitelist content alias =
  JS.moduleToBuilder items
  where
    refs = scanRuntimeRefsFiltered runtimeWhitelist content
    items =
      [JS.RawJS (moduleHeader alias)]
        ++ maybe [] (: []) (runtimeImportItem refs)
        ++ [JS.RawJS (BB.char7 '\n' <> Text.encodeUtf8Builder content <> BB.char7 '\n')]
        ++ namespaceItems alias content

-- | Header comment for generated FFI ES module.
moduleHeader :: String -> Builder
moduleHeader alias =
  "// FFI module: " <> BB.stringUtf8 alias <> "\n\
  \// Auto-generated by the Canopy compiler. Do not edit.\n\n"

-- | Build a runtime import item from scanned references.
runtimeImportItem :: Set Text.Text -> Maybe JS.ModuleItem
runtimeImportItem refs
  | Set.null refs = Nothing
  | otherwise =
      Just (JS.ImportNamedRaw (map textToBs (Set.toAscList refs)) "'../canopy-runtime.js'")

-- | Convert 'Text.Text' to strict 'ByteString' via UTF-8 encoding.
textToBs :: Text.Text -> ByteString
textToBs = Text.encodeUtf8

-- | Generate namespace and globalThis registration as 'ModuleItem' values.
--
-- Uses a merge pattern (@Object.assign(globalThis.Alias || {}, {...})@) so that
-- multiple FFI files sharing the same alias accumulate rather than overwrite.
-- Internal @_@-prefixed names are also assigned directly on @globalThis@.
namespaceItems :: String -> Text.Text -> [JS.ModuleItem]
namespaceItems alias content =
  mergeItem ++ internalItem
  where
    contentLines = Text.lines content
    functions = FFI.extractFFIFunctions contentLines
    funcPairs = map (\ef -> (textToBs (FFI._extractedName ef), textToBs (actualJSVarName ef))) functions
    internalNames = extractTopLevelInternalNames contentLines
    allInternals = Set.toAscList (Set.fromList internalNames)
    aliasBs = textToBs (Text.pack alias)
    mergeItem = [JS.RawJS (mergeIntoGlobalThis aliasBs funcPairs) | not (null funcPairs)]
    internalItem = [JS.GlobalThisAssignRaw (map textToBs allInternals) | not (null allInternals)]

-- | Emit @globalThis.Alias = Object.assign(globalThis.Alias || {}, { f1, f2 });@
--
-- Each pair is @(canopyName, jsVarName)@. When they are equal, shorthand
-- property syntax is used (@{ f }@); when they differ, explicit syntax is
-- used (@{ cssScoped: _VirtualDom_cssScoped }@).  Using a merge ensures
-- that multiple FFI modules with the same alias accumulate their exported
-- functions instead of clobbering each other.
mergeIntoGlobalThis :: ByteString -> [(ByteString, ByteString)] -> BB.Builder
mergeIntoGlobalThis alias pairs =
  "globalThis."
    <> BB.byteString alias
    <> " = Object.assign(globalThis."
    <> BB.byteString alias
    <> " || {}, { "
    <> BB.byteString (BS.intercalate ", " (map renderPair pairs))
    <> " });\n"
  where
    renderPair (k, v)
      | k == v    = k
      | otherwise = k <> ": " <> v

-- | Get the actual JavaScript variable name for an extracted FFI function.
actualJSVarName :: FFI.ExtractedFFI -> Text.Text
actualJSVarName ef =
  maybe (FFI._extractedName ef) id (FFI._extractedJSName ef)

-- | Extract only top-level @_@-prefixed @var@ and @function@ declarations.
--
-- Unlike 'FFI.extractInternalNames' (which trims leading whitespace and thus
-- picks up declarations inside function bodies), this only matches lines with
-- no leading whitespace. In ESM mode only module-scope declarations can be
-- assigned to @globalThis@ as bare names.
extractTopLevelInternalNames :: [Text.Text] -> [Text.Text]
extractTopLevelInternalNames = concatMap extractTopLevel
  where
    extractTopLevel line
      | "var _" `Text.isPrefixOf` line =
          let name = Text.takeWhile isIdentChar (Text.drop 4 line)
          in [name | Text.length name > 1]
      | "function _" `Text.isPrefixOf` line =
          let name = Text.takeWhile isIdentChar (Text.drop 9 line)
          in [name | Text.length name > 1]
      | otherwise = []


-- | Scan FFI content for references to runtime symbols.
--
-- Finds all @_Prefix_name@ patterns and currying helpers (@F2@, @A3@, etc.)
-- that appear in the FFI source text, then subtracts any symbols that are
-- locally defined within the FFI file itself (via @var@ or @function@
-- declarations at line start). Only externally-referenced symbols are
-- returned — these must be imported from @canopy-runtime.js@.
--
-- @since 0.20.0
scanRuntimeRefs :: Text.Text -> Set Text.Text
scanRuntimeRefs content =
  Set.difference allRefs localDefs
  where
    allRefs = Set.union (scanPrefixedRefs content) (scanCurryingRefs content)
    localDefs = scanLocalDefinitions content

-- | Like 'scanRuntimeRefs' but intersects the result with a whitelist.
scanRuntimeRefsFiltered :: Set Text.Text -> Text.Text -> Set Text.Text
scanRuntimeRefsFiltered whitelist content =
  Set.intersection (scanRuntimeRefs content) whitelist

-- | Scan FFI content for locally defined symbols.
--
-- Extracts names from lines starting with @var NAME@ or @function NAME@,
-- which indicate symbols defined within the FFI file itself rather than
-- imported from the runtime.
scanLocalDefinitions :: Text.Text -> Set Text.Text
scanLocalDefinitions content =
  Set.fromList (concatMap extractLocalDecl (Text.lines content))

-- | Extract a local declaration name from a single line.
extractLocalDecl :: Text.Text -> [Text.Text]
extractLocalDecl line
  | Just rest <- Text.stripPrefix "var " line =
      [Text.takeWhile isIdentChar rest]
  | Just rest <- Text.stripPrefix "function " line =
      [Text.takeWhile isIdentChar rest]
  | otherwise = []

-- | Scan for @_Prefix_name@ style runtime references.
scanPrefixedRefs :: Text.Text -> Set Text.Text
scanPrefixedRefs content =
  Set.fromList (concatMap (findPrefixed content) runtimePrefixes)

-- | Find all occurrences of a given prefix in text.
findPrefixed :: Text.Text -> Text.Text -> [Text.Text]
findPrefixed content prefix =
  extractIdentifiers prefix content

-- | Extract identifiers starting with a given prefix from text.
extractIdentifiers :: Text.Text -> Text.Text -> [Text.Text]
extractIdentifiers prefix txt =
  case Text.breakOn prefix txt of
    (_, remainder)
      | Text.null remainder -> []
      | otherwise ->
          let ident = Text.takeWhile isIdentChar remainder
              rest = Text.drop (Text.length ident) remainder
           in [ident | Text.length ident > Text.length prefix]
                ++ extractIdentifiers prefix rest

-- | Check if a character is valid in a JavaScript identifier.
isIdentChar :: Char -> Bool
isIdentChar c =
  (c >= 'a' && c <= 'z')
    || (c >= 'A' && c <= 'Z')
    || (c >= '0' && c <= '9')
    || c == '_'
    || c == '$'

-- | Scan for currying helper references (F2–F9, A2–A9, F).
scanCurryingRefs :: Text.Text -> Set Text.Text
scanCurryingRefs content =
  Set.fromList (filter (isReferencedIn content) curryingHelpers)

-- | Check if a name appears as a standalone identifier in content.
--
-- Avoids matching substrings by checking that the character before
-- and after the name is not an identifier character.
isReferencedIn :: Text.Text -> Text.Text -> Bool
isReferencedIn content name =
  checkOccurrences name content
  where
    checkOccurrences n txt =
      case Text.breakOn n txt of
        (_, remainder)
          | Text.null remainder -> False
          | otherwise ->
              let before = Text.takeEnd 1 (Text.take (Text.length txt - Text.length remainder) txt)
                  after = Text.take 1 (Text.drop (Text.length n) remainder)
                  beforeOk = Text.null before || not (Text.any isIdentChar before)
                  afterOk = Text.null after || not (Text.any isIdentChar after)
               in (beforeOk && afterOk)
                    || checkOccurrences n (Text.drop (Text.length n) remainder)
