{-# LANGUAGE OverloadedStrings #-}

-- | ESM runtime module generation.
--
-- Generates @canopy-runtime.js@, an ES module that re-exports all runtime
-- primitives. The function bodies are identical to the IIFE runtime — only
-- the declaration style changes (@var@ → @export const@\/@export function@).
--
-- The generated module contains:
--
--   * Currying helpers (F2–F9, A2–A9) from "Generate.JavaScript.Functions"
--   * Core runtime (_Utils_eq, _List_Nil, _Basics_add, …) from "Generate.JavaScript.Runtime"
--   * FFI runtime validators from "Generate.JavaScript.FFIRuntime"
--   * Debug flag (@export const __canopy_debug@)
--
-- The export block is derived dynamically by scanning the runtime content
-- for top-level @var@ and @function@ declarations. This ensures the
-- export list can never go out of sync with the runtime definitions.
--
-- @since 0.20.0
module Generate.JavaScript.ESM.Runtime
  ( generateRuntime,
  )
where

import Data.ByteString (ByteString)
import qualified Data.ByteString.Char8 as BS8
import Data.ByteString.Builder (Builder)
import qualified Data.ByteString.Builder as BB
import qualified Data.ByteString.Lazy as LBS
import Data.Set (Set)
import qualified Data.Set as Set
import qualified Generate.JavaScript.Builder as JS
import qualified Generate.JavaScript.FFIRuntime as FFIRuntime
import qualified Generate.JavaScript.Functions as Functions
import qualified Generate.JavaScript.Name as JsName
import qualified Generate.JavaScript.Runtime as Runtime
import qualified Generate.Mode as Mode

-- | Generate the complete @canopy-runtime.js@ ES module.
--
-- Wraps the existing IIFE runtime content in an ESM shell. All top-level
-- @var@ and @function@ declarations are scanned and automatically added
-- to the @Object.assign(globalThis, ...)@ and @export {}@ blocks.
--
-- This approach avoids duplicating the runtime source — the same
-- embedded strings from 'Runtime.embeddedRuntime' and
-- 'Functions.functions' are reused verbatim, and the export list
-- is derived from them so it can never go out of sync.
--
-- @since 0.20.0
generateRuntime :: Mode.Mode -> Builder
generateRuntime mode =
  JS.moduleToBuilder items
  where
    runtimeBody = Functions.functions <> Runtime.embeddedRuntime
    ffiRuntimeBody = FFIRuntime.embeddedRuntimeForMode mode
    runtimeBs = materialize runtimeBody
    ffiBs = materialize ffiRuntimeBody
    runtimeSyms = scanTopLevelDecls runtimeBs
    ffiSyms = scanTopLevelDecls ffiBs
    allSymbols = Set.toAscList (Set.insert "__canopy_debug" (Set.union runtimeSyms ffiSyms))
    items =
      [ JS.RawJS header,
        JS.ModuleStmt (debugDeclaration mode),
        JS.RawJS runtimeBody,
        JS.RawJS ffiRuntimeBody,
        JS.GlobalThisAssignRaw allSymbols,
        JS.ExportLocalsRaw allSymbols
      ]

-- | ESM file header comment.
header :: Builder
header =
  "// canopy-runtime.js — Canopy runtime as ES module\n\
  \// Auto-generated by the Canopy compiler. Do not edit.\n\n"

-- | Debug flag declaration for ESM as a typed AST statement.
debugDeclaration :: Mode.Mode -> JS.Stmt
debugDeclaration (Mode.Dev {}) = JS.Var debugName (JS.Bool True)
debugDeclaration (Mode.Prod {}) = JS.Var debugName (JS.Bool False)

-- | The JS name for the debug flag.
debugName :: JsName.Name
debugName = JsName.fromBuilder "__canopy_debug"

-- | Materialize a 'Builder' into a strict 'ByteString' for scanning.
materialize :: Builder -> ByteString
materialize = LBS.toStrict . BB.toLazyByteString

-- | Scan a JavaScript source 'ByteString' for top-level @var@ and @function@
-- declarations, returning the set of declared symbol names.
--
-- Matches lines starting with @var NAME@ or @function NAME@ at column 0.
-- This is reliable because the embedded runtime uses consistent formatting
-- with no indentation for top-level declarations.
scanTopLevelDecls :: ByteString -> Set ByteString
scanTopLevelDecls content =
  Set.fromList (concatMap extractDecl (BS8.lines content))

-- | Extract a declaration name from a single line, if it starts with
-- @var@ or @function@ at column 0.
extractDecl :: ByteString -> [ByteString]
extractDecl line
  | Just rest <- BS8.stripPrefix "var " line =
      [BS8.takeWhile isIdentChar rest]
  | Just rest <- BS8.stripPrefix "function " line =
      [BS8.takeWhile isIdentChar rest]
  | otherwise = []

-- | Check if a character is valid in a JavaScript identifier.
isIdentChar :: Char -> Bool
isIdentChar c =
  (c >= 'a' && c <= 'z')
    || (c >= 'A' && c <= 'Z')
    || (c >= '0' && c <= '9')
    || c == '_'
    || c == '$'
