{-# LANGUAGE OverloadedStrings #-}

-- | ESM runtime module generation.
--
-- Generates @canopy-runtime.js@, an ES module that re-exports all runtime
-- primitives. The function bodies are identical to the IIFE runtime — only
-- the declaration style changes (@var@ → @export const@\/@export function@).
--
-- The generated module contains:
--
--   * Currying helpers (F2–F9, A2–A9) from "Generate.JavaScript.Functions"
--   * Core runtime (_Utils_eq, _List_Nil, _Basics_add, …) from "Generate.JavaScript.Runtime"
--   * FFI runtime validators from "Generate.JavaScript.FFIRuntime"
--   * Debug flag (@export const __canopy_debug@)
--
-- The export block is derived dynamically by scanning the runtime content
-- for top-level @var@ and @function@ declarations. This ensures the
-- export list can never go out of sync with the runtime definitions.
--
-- @since 0.20.0
module Generate.JavaScript.ESM.Runtime
  ( generateRuntime,
    allRuntimeExportSymbols,
  )
where

import Data.ByteString (ByteString)
import Data.ByteString.Builder (Builder)
import Data.Set (Set)
import qualified Data.Set as Set
import qualified Generate.JavaScript.Builder as JS
import qualified Generate.JavaScript.FFIRuntime as FFIRuntime
import qualified Generate.JavaScript.Functions as Functions
import qualified Generate.JavaScript.Name as JsName
import qualified Generate.JavaScript.Runtime as Runtime
import qualified Generate.JavaScript.Runtime.Registry as Registry
import qualified Generate.Mode as Mode

-- | Generate the complete @canopy-runtime.js@ ES module.
--
-- Wraps the existing IIFE runtime content in an ESM shell. The export list
-- is derived from the runtime registry (AST-parsed at build time) and
-- static name lists for currying helpers, FFI runtime objects, and HMR
-- helpers. No byte/text scanning occurs.
--
-- In dev mode, HMR helper functions (@_Platform_getModel@,
-- @_Platform_hotSwap@) are injected into the runtime.
--
-- @since 0.20.0
generateRuntime :: Mode.Mode -> Builder
generateRuntime mode =
  JS.moduleToBuilder items
  where
    runtimeBody = Functions.functions <> Runtime.embeddedRuntime
    ffiRuntimeBody = FFIRuntime.embeddedRuntimeForMode mode
    hmrBody = hmrRuntimeHelpers mode
    allSymbols = Set.toAscList (allRuntimeExportSymbols mode)
    items =
      [ JS.RawJS header,
        JS.ModuleStmt (debugDeclaration mode),
        JS.RawJS runtimeBody,
        JS.RawJS ffiRuntimeBody,
        JS.RawJS hmrBody,
        JS.GlobalThisAssignRaw allSymbols,
        JS.ExportLocalsRaw allSymbols
      ]

-- | Compute the full set of symbols to export from @canopy-runtime.js@.
--
-- Combines registry-derived runtime names, currying helpers, FFI runtime
-- namespace objects, HMR helpers (dev mode only), and the debug flag.
-- All names are derived statically — no byte scanning required.
allRuntimeExportSymbols :: Mode.Mode -> Set ByteString
allRuntimeExportSymbols mode =
  Registry.exportedRuntimeSymbols
    `Set.union` modeSpecificSymbols mode

-- | Symbols only present in specific compile modes.
modeSpecificSymbols :: Mode.Mode -> Set ByteString
modeSpecificSymbols (Mode.Dev {}) = Set.fromList Registry.hmrSymbols
modeSpecificSymbols (Mode.Prod {}) = Set.empty

-- | ESM file header comment.
header :: Builder
header =
  "// canopy-runtime.js — Canopy runtime as ES module\n\
  \// Auto-generated by the Canopy compiler. Do not edit.\n\n"

-- | Debug flag declaration for ESM as a typed AST statement.
debugDeclaration :: Mode.Mode -> JS.Stmt
debugDeclaration (Mode.Dev {}) = JS.Var debugName (JS.Bool True)
debugDeclaration (Mode.Prod {}) = JS.Var debugName (JS.Bool False)

-- | The JS name for the debug flag.
debugName :: JsName.Name
debugName = JsName.fromBuilder "__canopy_debug"

-- HMR RUNTIME HELPERS

-- | Generate HMR runtime helper functions for dev mode.
--
-- In dev mode, injects @_Platform_getModel@ and @_Platform_hotSwap@
-- into the runtime. These are called by the per-module HMR acceptance
-- code generated by "Generate.JavaScript.ESM.HMR".
--
-- In prod mode, returns an empty builder (no HMR overhead).
--
-- @since 0.20.0
hmrRuntimeHelpers :: Mode.Mode -> Builder
hmrRuntimeHelpers (Mode.Prod {}) = mempty
hmrRuntimeHelpers (Mode.Dev {}) =
  "\n// HMR: Model state access for hot module replacement\n\
  \var _Platform_currentModel = undefined;\n\
  \var _Platform_currentStepper = undefined;\n\
  \\n\
  \function _Platform_getModel() {\n\
  \  return _Platform_currentModel;\n\
  \}\n\
  \\n\
  \function _Platform_hotSwap(newModule, oldModel) {\n\
  \  _Platform_currentModel = oldModel;\n\
  \  if (typeof _Platform_currentStepper === 'function') {\n\
  \    _Platform_currentStepper(oldModel, true);\n\
  \  }\n\
  \}\n\
  \\n\
  \function _Platform_trackModel(model) {\n\
  \  _Platform_currentModel = model;\n\
  \}\n\
  \\n\
  \function _Platform_trackStepper(stepper) {\n\
  \  _Platform_currentStepper = stepper;\n\
  \}\n"
