module Main exposing (main)

import Browser
import Html exposing (Html, text)


main : Program () Model Msg
main =
    Browser.sandbox { init = init, update = update, view = view }


type alias Model =
    String


type Msg
    = NoOp


init : Model
init =
    "Hello, Canopy!"


update : Msg -> Model -> Model
update msg model =
    case msg of
        NoOp ->
            model


view : Model -> Html Msg
view model =
    text model