{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}

-- | FFI code generation for the Canopy compiler.
--
-- This module is responsible for generating JavaScript FFI content,
-- function bindings, and runtime validators. It handles:
--
-- * Emitting raw FFI JavaScript source into the bundle
-- * Generating curried function bindings for Canopy<->JS interop
-- * Producing runtime type validators when strict mode is enabled
-- * Parsing \@canopy-type annotations from JSDoc comments
--
-- The 'FFIInfo' type carries all data needed to emit FFI JavaScript
-- code without relying on global state or MVars.
--
-- WARNING: NO HARDCODING OF FFI FILE PATHS!
-- All FFI file paths MUST come from the actual foreign import statements
-- in the source code, NOT hardcoded values.
--
-- @since 0.19.2
module Generate.JavaScript.FFI
  ( -- * Types
    FFIInfo (..),
    ffiFilePath,
    ffiContent,
    ffiAlias,
    ExtractedFFI (..),

    -- * Generation
    extractFFIAliases,
    generateFFIContent,
    generateFFIValidators,

    -- * Internal (exported for testing)
    extractCanopyTypeFunctions,
    extractFFIFunctions,
    extractCanopyType,
    findFunctionName,
    isValidJsIdentifier,
    escapeJsString,
    trim,
  )
where

import qualified AST.Optimized as Opt
import qualified Data.Char as Char
import Control.Lens (makeLenses)
import qualified Data.Binary as Binary
import Data.ByteString.Builder (Builder)
import qualified Data.ByteString.Builder as BB
import qualified Data.List as List
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import qualified Canopy.Data.Name as Name
import Data.Set (Set)
import qualified Data.Set as Set
import qualified Data.Text as Text
import qualified Data.Text.Encoding as TextEnc
import qualified FFI.TypeParser as TypeParser
import FFI.Types (BindingMode (..))
import qualified FFI.Validator as Validator
import qualified Generate.Mode as Mode

-- | Graph of optimized global definitions.
type Graph = Map Opt.Global Opt.Node

-- FFI INFO TYPE

-- | FFI information for JavaScript generation.
--
-- Carries everything needed to emit FFI JavaScript code in the bundle
-- without relying on global storage.  'FilePath' clarifies path semantics,
-- 'Text' captures Unicode source content, and 'Name.Name' preserves the
-- alias that appeared in the @foreign import@ declaration.
data FFIInfo = FFIInfo
  { _ffiFilePath :: !FilePath     -- ^ Path to the JavaScript file
  , _ffiContent  :: !Text.Text    -- ^ Content of the JavaScript file
  , _ffiAlias    :: !Name.Name    -- ^ Alias used in the import statement
  } deriving (Eq, Show)

-- | Manual 'Binary' instance to avoid depending on orphan instances for
-- 'Text' and to use the project-standard 'Utf8' serialisation for 'Name'.
instance Binary.Binary FFIInfo where
  put (FFIInfo path content alias) = do
    Binary.put path
    Binary.put (TextEnc.encodeUtf8 content)
    Binary.put alias
  get = do
    path <- Binary.get
    contentBytes <- Binary.get
    alias <- Binary.get
    return (FFIInfo path (TextEnc.decodeUtf8 contentBytes) alias)

makeLenses ''FFIInfo

-- EXTRACT FFI ALIASES

-- | Extract FFI alias names from FFI info map.
--
-- Used to identify which module names correspond to FFI modules vs application modules.
-- FFI modules use direct JavaScript access, while application modules use qualified names.
--
-- @since 0.19.1
extractFFIAliases :: Map String FFIInfo -> Set Name.Name
extractFFIAliases ffiInfos =
  Set.fromList (map _ffiAlias (Map.elems ffiInfos))

-- GENERATE FFI CONTENT

-- | Generate FFI JavaScript content to include in bundle.
--
-- Receives FFI information directly through the compilation pipeline
-- instead of using global storage, eliminating MVar deadlock issues.
-- When FFI strict mode is enabled, also generates runtime validators.
generateFFIContent :: Mode.Mode -> Graph -> Map String FFIInfo -> Builder
generateFFIContent mode graph ffiInfos =
  if Map.null ffiInfos
     then mempty
     else mconcat parts <> validators
  where
    parts =
      [ "\n// FFI JavaScript content from external files\n" ]
        ++ Map.foldrWithKey formatFFIFileFromInfo [] ffiInfos
        ++ [ "\n// FFI function bindings\n" ]
        ++ Map.foldrWithKey (generateFFIBindingsFromInfo mode graph) [] ffiInfos
    validators =
      if Mode.isFFIStrict mode
        then generateFFIValidators mode ffiInfos
        else mempty

-- GENERATE FFI VALIDATORS

-- | Generate FFI validators for all function return types.
--
-- Uses the 'Mode' to derive 'ValidatorConfig', enabling CLI control
-- over strict mode and debug verbosity in generated validators.
--
-- @since 0.19.2
generateFFIValidators :: Mode.Mode -> Map String FFIInfo -> Builder
generateFFIValidators mode ffiInfos =
  if Map.null ffiInfos
     then mempty
     else mconcat parts
  where
    config = modeToValidatorConfig mode

    parts =
      [ "\n// FFI type validators (generated by canopy)\n" ]
        ++ Map.foldrWithKey collectValidators [] ffiInfos

    collectValidators :: String -> FFIInfo -> [Builder] -> [Builder]
    collectValidators _key info acc =
      let functions = extractCanopyTypeFunctions (Text.lines (_ffiContent info))
          validatorBuilders = concatMap (generateValidatorForFunction config) functions
      in validatorBuilders ++ acc

-- | Generate a validator builder for a single FFI function.
generateValidatorForFunction :: Validator.ValidatorConfig -> (Text.Text, Text.Text) -> [Builder]
generateValidatorForFunction config (_funcName, typeStr) =
  case Validator.parseReturnType typeStr of
    Just returnType ->
      [BB.byteString (TextEnc.encodeUtf8 (Validator.generateAllValidators config returnType))]
    Nothing -> []

-- | Derive a 'ValidatorConfig' from the compilation 'Mode'.
--
-- Maps CLI flags to validator configuration:
--
-- * Strict mode is always on when validators are generated
--   (the on\/off is handled by 'Mode.isFFIStrict')
-- * Debug mode is controlled by @--ffi-debug@
--
-- @since 0.19.2
modeToValidatorConfig :: Mode.Mode -> Validator.ValidatorConfig
modeToValidatorConfig mode =
  Validator.ValidatorConfig
    { Validator._configStrictMode = True
    , Validator._configValidateOpaque = False
    , Validator._configDebugMode = Mode.isFFIDebug mode
    }

-- FORMAT FFI FILE CONTENT

-- | Format FFI file content for inclusion using FFIInfo.
formatFFIFileFromInfo :: String -> FFIInfo -> [Builder] -> [Builder]
formatFFIFileFromInfo _key info acc =
  ("\n// From " <> BB.stringUtf8 (_ffiFilePath info) <> "\n")
    : BB.byteString (TextEnc.encodeUtf8 (_ffiContent info))
    : "\n"
    : acc

-- GENERATE FFI BINDINGS

-- | Generate JavaScript variable bindings for FFI functions using FFIInfo with proper aliases.
generateFFIBindingsFromInfo :: Mode.Mode -> Graph -> String -> FFIInfo -> [Builder] -> [Builder]
generateFFIBindingsFromInfo mode graph _key info acc
  | not (isValidJsIdentifier aliasStr) = acc
  | otherwise =
      case extractFFIFunctionBindings mode graph path contentText aliasStr of
        [] -> acc
        bindings ->
          ("\n// Bindings for " <> BB.stringUtf8 path <> "\n")
            : ("var " <> BB.stringUtf8 aliasStr <> " = " <> BB.stringUtf8 aliasStr <> " || {};\n")
            : map (<> "\n") bindings ++ ["\n"] ++ acc
  where
    path = _ffiFilePath info
    contentText = _ffiContent info
    aliasStr = Name.toChars (_ffiAlias info)

-- | Extract and generate bindings for FFI functions from JavaScript content.
extractFFIFunctionBindings :: Mode.Mode -> Graph -> String -> Text.Text -> String -> [Builder]
extractFFIFunctionBindings mode graph path content alias =
  concatMap (generateFFIBinding mode graph path alias) functions
  where
    functions = extractFFIFunctions (Text.lines content)

-- PARSE CANOPY TYPE ANNOTATIONS

-- | Extracted FFI function info from JSDoc annotations.
data ExtractedFFI = ExtractedFFI
  { _extractedName :: !Text.Text
    -- ^ Function name (JS side or from @canopy-name)
  , _extractedType :: !Text.Text
    -- ^ Type annotation from @canopy-type
  , _extractedMode :: !BindingMode
    -- ^ Binding mode from @canopy-bind
  , _extractedCanopyName :: !(Maybe Text.Text)
    -- ^ Optional Canopy-side name override
  } deriving (Eq, Show)

-- | Extract functions that have \@canopy-type annotations from JavaScript source lines.
--
-- Operates on 'Text' lines directly to avoid intermediate @[Char]@
-- allocation from the FFI content.
--
-- @since 0.19.2
extractCanopyTypeFunctions :: [Text.Text] -> [(Text.Text, Text.Text)]
extractCanopyTypeFunctions = List.map toSimple . extractFFIFunctions
  where
    toSimple ef = (effectiveName ef, _extractedType ef)

-- | Get the effective Canopy-side name for an extracted FFI function.
effectiveName :: ExtractedFFI -> Text.Text
effectiveName ef =
  maybe (_extractedName ef) id (_extractedCanopyName ef)

-- | Extract full FFI function information from JavaScript source lines.
extractFFIFunctions :: [Text.Text] -> [ExtractedFFI]
extractFFIFunctions [] = []
extractFFIFunctions allLines@(_:_) =
  extractFromBlocks allLines

-- | Extract FFI functions from JSDoc blocks in source lines.
extractFromBlocks :: [Text.Text] -> [ExtractedFFI]
extractFromBlocks [] = []
extractFromBlocks (line:rest)
  | isJSDocStart line =
      let (block, remaining) = takeJSDocBlock (line:rest)
       in case parseFFIBlock block rest of
            Just ef -> ef : extractFromBlocks remaining
            Nothing -> extractFromBlocks remaining
  | otherwise = extractFromBlocks rest

-- | Check if a line starts a JSDoc comment.
isJSDocStart :: Text.Text -> Bool
isJSDocStart line = "/**" `Text.isPrefixOf` Text.stripStart line

-- | Take a complete JSDoc block and the remaining lines.
takeJSDocBlock :: [Text.Text] -> ([Text.Text], [Text.Text])
takeJSDocBlock [] = ([], [])
takeJSDocBlock (line:rest)
  | "*/" `Text.isInfixOf` line = ([line], rest)
  | otherwise =
      let (block, remaining) = takeJSDocBlock rest
       in (line:block, remaining)

-- | Parse a JSDoc block into an ExtractedFFI.
parseFFIBlock :: [Text.Text] -> [Text.Text] -> Maybe ExtractedFFI
parseFFIBlock block followingLines = do
  canopyType <- findAnnotationInBlock "@canopy-type " block
  let bindMode = parseBlockBindMode block
      canopyName = findAnnotationInBlock "@canopy-name " block
      jsFuncName = findFunctionName followingLines
  funcName <- findAnnotationInBlock "@name " block
                <|> jsFuncName
  Just (ExtractedFFI funcName canopyType bindMode canopyName)

-- | Find a specific annotation value in a JSDoc block.
findAnnotationInBlock :: Text.Text -> [Text.Text] -> Maybe Text.Text
findAnnotationInBlock _ [] = Nothing
findAnnotationInBlock tag (line:rest) =
  let stripped = stripJSDocLeader line
   in case Text.stripPrefix tag stripped of
        Just value -> Just (Text.strip value)
        Nothing -> findAnnotationInBlock tag rest

-- | Strip JSDoc leader characters from a line.
stripJSDocLeader :: Text.Text -> Text.Text
stripJSDocLeader = Text.dropWhile (\c -> c == ' ' || c == '*')

-- | Parse binding mode from a JSDoc block.
parseBlockBindMode :: [Text.Text] -> BindingMode
parseBlockBindMode [] = FunctionCall
parseBlockBindMode (line:rest) =
  case findAnnotationInBlock "@canopy-bind " [line] of
    Just value -> parseBindModeText value
    Nothing -> parseBlockBindMode rest

-- | Parse binding mode from the text after @canopy-bind.
parseBindModeText :: Text.Text -> BindingMode
parseBindModeText txt =
  case Text.words txt of
    ["method", name] -> MethodCall name
    ["get", name] -> PropertyGet name
    ["set", name] -> PropertySet name
    ["new", name] -> ConstructorCall name
    _ -> FunctionCall

-- | Alternative combinator for Maybe.
(<|>) :: Maybe a -> Maybe a -> Maybe a
(<|>) (Just x) _ = Just x
(<|>) Nothing y = y

-- | Extract \@canopy-type annotation from a single line.
--
-- Uses 'Text.isInfixOf' (O(n) with fast string matching) instead of
-- the previous 'List.isInfixOf' (O(n*m) on @[Char]@).
--
-- @since 0.19.2
extractCanopyType :: Text.Text -> Maybe Text.Text
extractCanopyType line
  | " * @canopy-type " `Text.isInfixOf` line =
      fmap Text.strip (Text.stripPrefix "@canopy-type " (Text.dropWhile (/= '@') line))
  | otherwise = Nothing

-- | Find the function name in the following lines.
--
-- Handles both @function name(...)@ and @async function name(...)@.
-- Operates on 'Text' lines to avoid @[Char]@ allocation.
--
-- @since 0.19.2
findFunctionName :: [Text.Text] -> Maybe Text.Text
findFunctionName [] = Nothing
findFunctionName (line:rest) =
  let trimmed = Text.strip line
      stripped = stripAsyncPrefix trimmed
  in if "function " `Text.isPrefixOf` stripped
       then extractNameAfterFunction stripped
       else findFunctionName rest
  where
    stripAsyncPrefix s
      | "async " `Text.isPrefixOf` s = Text.strip (Text.drop 6 s)
      | otherwise = s
    extractNameAfterFunction s =
      let after = Text.strip (Text.dropWhile (/= ' ') s)
          name = Text.takeWhile (\c -> c /= '(' && c /= ' ') after
      in if Text.null name then findFunctionName rest else Just name

-- GENERATE FUNCTION BINDINGS

-- | Generate JavaScript binding for an extracted FFI function.
--
-- Validates that the function name is a safe JavaScript identifier
-- before generating any code. For binding modes other than FunctionCall,
-- generates inline JavaScript expressions (method calls, property access,
-- constructor invocations) instead of delegating to a JS function.
--
-- @since 0.20.0
generateFFIBinding :: Mode.Mode -> Graph -> String -> String -> ExtractedFFI -> [Builder]
generateFFIBinding mode _graph _filePath alias ef
  | not (isValidJsIdentifier canopyName) = []
  | otherwise =
      case _extractedMode ef of
        FunctionCall -> generateFunctionCallBinding mode alias ef
        MethodCall methodName -> generateMethodBinding alias ef methodName
        PropertyGet propName -> generatePropertyGetBinding alias ef propName
        PropertySet propName -> generatePropertySetBinding alias ef propName
        ConstructorCall className -> generateConstructorBinding alias ef className
  where
    canopyName = Text.unpack (effectiveName ef)

-- | Generate binding for a standard function call.
generateFunctionCallBinding :: Mode.Mode -> String -> ExtractedFFI -> [Builder]
generateFunctionCallBinding mode alias ef =
  let canopyNameText = effectiveName ef
      canopyName = Text.unpack canopyNameText
      canopyTypeText = _extractedType ef
      arity = maybe 0 TypeParser.countArity (TypeParser.parseType canopyTypeText)
      jsVarB = BB.stringUtf8 ("$author$project$" ++ alias ++ "$" ++ canopyName)
      aliasB = BB.stringUtf8 alias
      funcNameB = BB.byteString (TextEnc.encodeUtf8 canopyNameText)
      callPathB = "'" <> escapeJsString (Text.pack alias <> "." <> canopyNameText) <> "'"
   in if Mode.isFFIStrict mode
        then generateValidatedBinding jsVarB aliasB funcNameB arity canopyTypeText callPathB
        else generateSimpleBinding jsVarB aliasB funcNameB arity

-- | Generate binding for a method call: @obj.method(args)@.
generateMethodBinding :: String -> ExtractedFFI -> Text.Text -> [Builder]
generateMethodBinding alias ef methodName =
  let canopyNameText = effectiveName ef
      canopyName = Text.unpack canopyNameText
      arity = maybe 0 TypeParser.countArity (TypeParser.parseType (_extractedType ef))
      jsVarB = BB.stringUtf8 ("$author$project$" ++ alias ++ "$" ++ canopyName)
      aliasB = BB.stringUtf8 alias
      nameB = BB.byteString (TextEnc.encodeUtf8 canopyNameText)
      methodB = BB.byteString (TextEnc.encodeUtf8 methodName)
      args = map (\i -> "_" <> BB.intDec i) [0 .. arity - 1]
      argList = mconcat (List.intersperse ", " args)
      restArgs = mconcat (List.intersperse ", " (drop 1 args))
      body = "_0." <> methodB <> "(" <> restArgs <> ")"
      funcExpr = wrapArity arity ("function(" <> argList <> ") { return " <> body <> "; }")
   in ["var " <> jsVarB <> " = " <> funcExpr <> ";", aliasB <> "." <> nameB <> " = " <> jsVarB <> ";"]

-- | Generate binding for a property getter: @obj.propName@.
generatePropertyGetBinding :: String -> ExtractedFFI -> Text.Text -> [Builder]
generatePropertyGetBinding alias ef propName =
  let canopyNameText = effectiveName ef
      canopyName = Text.unpack canopyNameText
      jsVarB = BB.stringUtf8 ("$author$project$" ++ alias ++ "$" ++ canopyName)
      aliasB = BB.stringUtf8 alias
      nameB = BB.byteString (TextEnc.encodeUtf8 canopyNameText)
      propB = BB.byteString (TextEnc.encodeUtf8 propName)
      body = "_0." <> propB
      funcExpr = "function(_0) { return " <> body <> "; }"
   in ["var " <> jsVarB <> " = " <> funcExpr <> ";", aliasB <> "." <> nameB <> " = " <> jsVarB <> ";"]

-- | Generate binding for a property setter: @obj.propName = val@.
generatePropertySetBinding :: String -> ExtractedFFI -> Text.Text -> [Builder]
generatePropertySetBinding alias ef propName =
  let canopyNameText = effectiveName ef
      canopyName = Text.unpack canopyNameText
      jsVarB = BB.stringUtf8 ("$author$project$" ++ alias ++ "$" ++ canopyName)
      aliasB = BB.stringUtf8 alias
      nameB = BB.byteString (TextEnc.encodeUtf8 canopyNameText)
      propB = BB.byteString (TextEnc.encodeUtf8 propName)
      body = "_0." <> propB <> " = _1"
      funcExpr = wrapArity 2 ("function(_0, _1) { " <> body <> "; }")
   in ["var " <> jsVarB <> " = " <> funcExpr <> ";", aliasB <> "." <> nameB <> " = " <> jsVarB <> ";"]

-- | Generate binding for a constructor call: @new ClassName(args)@.
generateConstructorBinding :: String -> ExtractedFFI -> Text.Text -> [Builder]
generateConstructorBinding alias ef className =
  let canopyNameText = effectiveName ef
      canopyName = Text.unpack canopyNameText
      arity = maybe 0 TypeParser.countArity (TypeParser.parseType (_extractedType ef))
      jsVarB = BB.stringUtf8 ("$author$project$" ++ alias ++ "$" ++ canopyName)
      aliasB = BB.stringUtf8 alias
      nameB = BB.byteString (TextEnc.encodeUtf8 canopyNameText)
      classB = BB.byteString (TextEnc.encodeUtf8 className)
      args = map (\i -> "_" <> BB.intDec i) [0 .. arity - 1]
      argList = mconcat (List.intersperse ", " args)
      body = "new " <> classB <> "(" <> argList <> ")"
      funcExpr = wrapArity arity ("function(" <> argList <> ") { return " <> body <> "; }")
   in ["var " <> jsVarB <> " = " <> funcExpr <> ";", aliasB <> "." <> nameB <> " = " <> jsVarB <> ";"]

-- | Wrap a function expression with F<N>() for currying when arity > 1.
wrapArity :: Int -> Builder -> Builder
wrapArity arity funcExpr
  | arity <= 1 = funcExpr
  | otherwise = "F" <> BB.intDec arity <> "(" <> funcExpr <> ")"

-- | Generate simple binding without validation.
--
-- All parameters are pre-converted to 'Builder' at the call site to avoid
-- intermediate @[Char]@ allocation in the hot path.
generateSimpleBinding :: Builder -> Builder -> Builder -> Int -> [Builder]
generateSimpleBinding jsVarB aliasB funcNameB arity =
  let wrapper = if arity <= 1 then mempty else "F" <> BB.intDec arity <> "("
      closing = if arity <= 1 then mempty else ")"
      namespaceBinding = aliasB <> "." <> funcNameB <> " = " <> wrapper <> funcNameB <> closing <> ";"
  in ["var " <> jsVarB <> " = " <> wrapper <> funcNameB <> closing <> ";", namespaceBinding]

-- | Generate binding with runtime validation wrapper.
--
-- All name parameters are pre-converted to 'Builder' at the call site.
-- The @canopyType@ and @callPath@ remain 'Text' since they are parsed
-- or escaped from source content.
generateValidatedBinding :: Builder -> Builder -> Builder -> Int -> Text.Text -> Builder -> [Builder]
generateValidatedBinding jsVarB aliasB funcNameB arity canopyType callPathB =
  let args = if arity <= 0 then [] else map (\i -> "_" <> BB.intDec i) [0 .. arity - 1]
      argList = mconcat (List.intersperse ", " args)
      returnType = extractReturnType canopyType
      validatorExpr = typeToValidator returnType
      wrappedCall = funcNameB <> "(" <> argList <> ")"
      validatedCall = validatorExpr <> "(" <> wrappedCall <> ", " <> callPathB <> ")"
      funcBody = "function(" <> argList <> ") { return " <> validatedCall <> "; }"
      wrapper = if arity <= 1 then mempty else "F" <> BB.intDec arity <> "("
      closing = if arity <= 1 then mempty else ")"
      binding = "var " <> jsVarB <> " = " <> wrapper <> funcBody <> closing <> ";"
      namespaceBinding = aliasB <> "." <> funcNameB <> " = " <> jsVarB <> ";"
  in [binding, namespaceBinding]

-- TYPE VALIDATORS

-- | Extract return type from a function type signature.
--
-- For @"Int -> String -> Bool"@, returns @"Bool"@.
-- For non-function types, returns the whole type string.
-- Uses 'Text' to avoid intermediate @[Char]@ allocation.
--
-- @since 0.19.2
extractReturnType :: Text.Text -> Text.Text
extractReturnType typeStr =
  let tokens = Text.words typeStr
      arrowIndices = findArrowIndices tokens 0 []
  in if null arrowIndices
       then typeStr
       else Text.unwords (drop (maximum arrowIndices + 1) tokens)
  where
    findArrowIndices :: [Text.Text] -> Int -> [Int] -> [Int]
    findArrowIndices [] _ acc = acc
    findArrowIndices (t:ts) idx acc
      | t == "->" = findArrowIndices ts (idx + 1) (idx : acc)
      | otherwise = findArrowIndices ts (idx + 1) acc

-- | Convert a type string to a @$validate@ Builder expression.
--
-- Uses 'Text' input to avoid intermediate @[Char]@ allocation.
--
-- @since 0.19.2
typeToValidator :: Text.Text -> Builder
typeToValidator typeStr =
  case Validator.parseFFIType typeStr of
    Just ffiType -> ffiTypeToValidator ffiType
    Nothing -> "$validate.Any"

-- | Convert FFIType to $validate expression as a Builder.
ffiTypeToValidator :: Validator.FFIType -> Builder
ffiTypeToValidator ffiType = case ffiType of
  Validator.FFIInt -> "$validate.Int"
  Validator.FFIFloat -> "$validate.Float"
  Validator.FFIString -> "$validate.String"
  Validator.FFIBool -> "$validate.Bool"
  Validator.FFIUnit -> "$validate.Unit"
  Validator.FFIList inner ->
    "$validate.List(" <> ffiTypeToValidator inner <> ")"
  Validator.FFIMaybe inner ->
    "$validate.Maybe(" <> ffiTypeToValidator inner <> ")"
  Validator.FFIResult errType valType ->
    "$validate.Result(" <> ffiTypeToValidator errType <> ", " <> ffiTypeToValidator valType <> ")"
  Validator.FFITask errType valType ->
    "$validate.Task(" <> ffiTypeToValidator errType <> ", " <> ffiTypeToValidator valType <> ")"
  Validator.FFITuple types ->
    "$validate.Tuple(" <> mconcat (List.intersperse ", " (map ffiTypeToValidator types)) <> ")"
  Validator.FFIOpaque name ->
    "$validate.Opaque('" <> BB.byteString (TextEnc.encodeUtf8 name) <> "')"
  Validator.FFIFunctionType _ _ ->
    "$validate.Function"
  Validator.FFIRecord _ ->
    "$validate.Record"

-- UTILITIES

-- | Trim leading and trailing whitespace from text.
--
-- Uses 'Text.strip' for O(n) whitespace removal without intermediate
-- @[Char]@ allocation.
--
-- @since 0.19.2
trim :: Text.Text -> Text.Text
trim = Text.strip

-- | Check whether a string is a valid JavaScript identifier.
--
-- Valid identifiers start with a letter, underscore, or dollar sign,
-- and subsequent characters may also include digits. This is used
-- as a defense-in-depth check for FFI names injected into generated
-- JavaScript code.
--
-- @since 0.19.2
isValidJsIdentifier :: String -> Bool
isValidJsIdentifier (c : cs) = isValidFirst c && all isValidRest cs
  where
    isValidFirst x = Char.isAlpha x || x == '_' || x == '$'
    isValidRest x = Char.isAlphaNum x || x == '_' || x == '$'
isValidJsIdentifier [] = False

-- | Escape text for safe inclusion in a JavaScript string literal.
--
-- Produces a 'Builder' directly, avoiding intermediate @[Char]@ allocation.
-- Escapes all characters that could break out of or corrupt a JS string:
--
-- * Backslash (@\\@) -- escape character itself
-- * Single quote (@\'@) -- string delimiter
-- * Double quote (@\"@) -- defense-in-depth for double-quoted contexts
-- * Newline (@\\n@) -- line terminator
-- * Carriage return (@\\r@) -- line terminator
-- * Null byte (@\\0@) -- string terminator in some engines
-- * U+2028 LINE SEPARATOR -- JS line terminator (pre-ES2019)
-- * U+2029 PARAGRAPH SEPARATOR -- JS line terminator (pre-ES2019)
--
-- @since 0.19.2
escapeJsString :: Text.Text -> Builder
escapeJsString = Text.foldl' (\b c -> b <> escapeJsChar c) mempty

escapeJsChar :: Char -> Builder
escapeJsChar '\\' = "\\\\"
escapeJsChar '\'' = "\\'"
escapeJsChar '"' = "\\\""
escapeJsChar '\n' = "\\n"
escapeJsChar '\r' = "\\r"
escapeJsChar '\0' = "\\0"
escapeJsChar '\x2028' = "\\u2028"
escapeJsChar '\x2029' = "\\u2029"
escapeJsChar c = BB.charUtf8 c
