{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedStrings #-}

-- | Fast incremental IIFE relinking with a content-hash short-circuit.
--
-- = Why this module exists
--
-- The whole-program code generator ("Generate.JavaScript".'Generate.JavaScript.generate')
-- re-runs expression code generation, minification, FFI scanning, runtime
-- emission and tree-shaking for /every/ build. In a dev loop a single-file
-- edit touches exactly one module, yet the entire program is re-emitted from
-- scratch — the throughput gate of the dev loop (see plan DEV-9).
--
-- This module factors the bundle into one self-contained JavaScript
-- /fragment/ per Canopy module, content-addresses each fragment, and on a
-- relink regenerates only the fragments whose module nodes actually changed.
-- Unchanged modules short-circuit on their content hash and reuse the
-- previously generated bytes verbatim, so a single-module edit performs
-- code generation for a single module instead of the whole program.
--
-- = Content hash
--
-- A module's content hash is the SHA-256 of the binary serialization of its
-- @'Map' 'Opt.Global' 'Opt.Node'@ partition, salted with a tag derived from
-- the build 'Mode.Mode' (dev vs. prod produce different bytes, so they must
-- hash differently). The 'Opt.Node' / 'Opt.Expr' / 'Opt.Global' 'Binary'
-- instances make this exact: byte-identical module nodes yield an identical
-- hash and thus a cache hit, and any change to a definition, its
-- dependencies, or a sibling in the same module flips the hash and forces a
-- regenerate of just that module.
--
-- = Determinism
--
-- Fragments are concatenated in ascending 'ModuleName.Canonical' order, so a
-- full link and an incremental relink that ends in the same graph state emit
-- byte-identical bundles. This is asserted by the test-suite (a relink after
-- a no-op edit equals a fresh full link).
--
-- @since 0.20.5
module Generate.JavaScript.Relink
  ( -- * Fragments and cache
    ModuleFragment (..),
    RelinkCache,
    emptyCache,
    cacheFragments,

    -- * Linking
    BundleOptions (..),
    defaultBundleOptions,
    linkBundle,
    assembleBundle,

    -- * Incremental relink
    RelinkResult (..),
    relinkIncremental,

    -- * Hashing (exposed for testing)
    moduleContentHash,
    modeTag,

    -- * Partitioning (exposed for testing)
    partitionByModule,
  )
where

import qualified AST.Optimized as Opt
import qualified Canopy.ModuleName as ModuleName
import Data.ByteString (ByteString)
import Data.ByteString.Builder (Builder)
import qualified Data.ByteString.Builder as BB
import qualified Data.ByteString.Lazy as LBS
import qualified Data.Binary as Binary
import qualified Data.Digest.Pure.SHA as SHA
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import Data.Set (Set)
import qualified Generate.JavaScript.ESM as ESM
import qualified Generate.Mode as Mode

-- TYPES

-- | Map of main entry points per module (matches the IIFE/ESM backends).
type Mains = Map ModuleName.Canonical Opt.Main

-- | The flat optimized graph: globals to their definitions.
type Graph = Map Opt.Global Opt.Node

-- | A single module's contribution to the bundle.
--
-- 'mfHash' content-addresses 'mfCode': two fragments with the same hash are
-- guaranteed to have identical bytes (the hash is computed over the module's
-- 'Opt.Node' partition plus the mode tag), so an incremental relink can reuse
-- a cached fragment without re-running code generation.
data ModuleFragment = ModuleFragment
  { -- | The module this fragment was generated from.
    mfHome :: !ModuleName.Canonical,
    -- | SHA-256 of the module nodes + mode tag (see 'moduleContentHash').
    mfHash :: !ByteString,
    -- | The generated JavaScript bytes for this module.
    mfCode :: !ByteString
  }
  deriving (Eq, Show)

-- | Cache of previously generated fragments, keyed by module.
--
-- A relink consults this map: when the freshly computed content hash for a
-- module matches the cached fragment's 'mfHash', the cached bytes are reused.
type RelinkCache = Map ModuleName.Canonical ModuleFragment

-- | An empty relink cache (forces a full generate on the first link).
emptyCache :: RelinkCache
emptyCache = Map.empty

-- | Build a 'RelinkCache' from a list of fragments.
cacheFragments :: [ModuleFragment] -> RelinkCache
cacheFragments = Map.fromList . map (\f -> (mfHome f, f))

-- | Static bundle scaffolding wrapped around the concatenated fragments.
--
-- The relinker is fragment-agnostic about the runtime/header/footer: it
-- treats them as opaque, edit-invariant bytes supplied by the caller (the
-- dev server computes them once at warm-up). Only the per-module fragments
-- are recomputed on edit.
data BundleOptions = BundleOptions
  { -- | Bytes emitted before any fragment (IIFE header, runtime, FFI, …).
    boPrefix :: !ByteString,
    -- | Bytes emitted after the last fragment (entry init, IIFE footer, …).
    boSuffix :: !ByteString
  }
  deriving (Eq, Show)

-- | Minimal IIFE scaffolding: opens and closes a strict-mode IIFE.
--
-- Mirrors the header/footer shape of the whole-program generator so the
-- relinked bundle is a runnable IIFE on its own for tests and benchmarks.
defaultBundleOptions :: BundleOptions
defaultBundleOptions =
  BundleOptions
    { boPrefix = "(function(scope){'use strict';\n",
      boSuffix = "\n}(typeof window !== 'undefined' ? window : this));"
    }

-- HASHING

-- | A short tag distinguishing build modes so dev and prod fragments hash
-- differently even for identical nodes.
modeTag :: Mode.Mode -> ByteString
modeTag (Mode.Dev {}) = "dev"
modeTag (Mode.Prod {}) = "prod"

-- | Content hash of a module's node partition under a given mode.
--
-- Serializes the @('Map' 'Opt.Global' 'Opt.Node')@ via its 'Binary' instance,
-- prefixes the mode tag, and takes the SHA-256 digest. Byte-identical inputs
-- yield identical hashes; any structural change flips the hash.
moduleContentHash :: Mode.Mode -> Map Opt.Global Opt.Node -> ByteString
moduleContentHash mode nodes =
  let !payload = LBS.fromChunks [modeTag mode, "\NUL"] <> Binary.encode nodes
   in LBS.toStrict (SHA.bytestringDigest (SHA.sha256 payload))

-- PARTITIONING

-- | Partition a global graph into per-module node maps.
--
-- Every global is bucketed under its home module ('Opt.Global' carries its
-- 'ModuleName.Canonical'). Only globals present in the graph are kept; the
-- result is the unit of fragment generation and content hashing.
partitionByModule :: Graph -> Map ModuleName.Canonical (Map Opt.Global Opt.Node)
partitionByModule graph =
  Map.foldlWithKey' insert Map.empty graph
  where
    insert acc global@(Opt.Global home _) node =
      Map.insertWith Map.union home (Map.singleton global node) acc

-- FRAGMENT GENERATION

-- | Generate a single module's fragment from its node partition.
--
-- Delegates the actual JavaScript emission to the per-module ESM generator,
-- which reuses the same expression code generation as the IIFE backend, then
-- attaches the content hash so the fragment can be cached and short-circuited.
generateFragment ::
  Mode.Mode ->
  Mains ->
  Graph ->
  Set Opt.Global ->
  ModuleName.Canonical ->
  Map Opt.Global Opt.Node ->
  ModuleFragment
generateFragment mode mains graph reachable home nodes =
  ModuleFragment
    { mfHome = home,
      mfHash = moduleContentHash mode nodes,
      mfCode = LBS.toStrict (BB.toLazyByteString code)
    }
  where
    -- 'ESM.generateModule' wants entries keyed by local 'Name' with the full
    -- (global, node) pair as the value; rebuild that shape from the partition.
    entries =
      Map.fromList
        [ (name, (global, node))
          | (global@(Opt.Global _ name), node) <- Map.toList nodes
        ]
    code = ESM.generateModule mode mains graph reachable home entries

-- LINKING

-- | Full link: generate every module fragment fresh and assemble the bundle.
--
-- This is the whole-program baseline. It returns both the assembled bundle
-- and the populated cache so a subsequent edit can relink incrementally.
linkBundle ::
  BundleOptions ->
  Mode.Mode ->
  Opt.GlobalGraph ->
  Mains ->
  (Builder, RelinkCache)
linkBundle opts mode globalGraph mains =
  (assembleBundle opts fragments, cacheFragments fragments)
  where
    Opt.GlobalGraph graph _ _ = globalGraph
    reachable = Map.keysSet graph
    fragments =
      [ generateFragment mode mains graph reachable home nodes
        | (home, nodes) <- Map.toAscList (partitionByModule graph)
      ]

-- | Concatenate the prefix, the fragments (ascending module order), and the
-- suffix into a single bundle 'Builder'.
assembleBundle :: BundleOptions -> [ModuleFragment] -> Builder
assembleBundle opts fragments =
  BB.byteString (boPrefix opts)
    <> foldMap (BB.byteString . mfCode) ordered
    <> BB.byteString (boSuffix opts)
  where
    ordered = Map.elems (cacheFragments fragments)

-- INCREMENTAL RELINK

-- | The outcome of an incremental relink.
data RelinkResult = RelinkResult
  { -- | The reassembled bundle.
    rrBundle :: !Builder,
    -- | The updated cache (reuse for the next relink).
    rrCache :: !RelinkCache,
    -- | Modules whose fragment was regenerated this relink.
    rrRegenerated :: !(Set ModuleName.Canonical),
    -- | Modules whose fragment was reused from the cache.
    rrReused :: !(Set ModuleName.Canonical)
  }

-- | Incrementally relink against a previous cache.
--
-- For each module in the new graph, the content hash is recomputed and
-- compared against the cached fragment:
--
--   * /hit/  — the hashes match: reuse the cached bytes (no code generation).
--   * /miss/ — absent or hash differs: regenerate just this module's fragment.
--
-- Modules that vanished from the graph are dropped. The result carries the
-- reassembled bundle, the refreshed cache, and per-module hit/miss accounting
-- (the regenerated set is empty exactly when nothing changed — the dev-loop
-- fast path).
relinkIncremental ::
  BundleOptions ->
  Mode.Mode ->
  RelinkCache ->
  Opt.GlobalGraph ->
  Mains ->
  RelinkResult
relinkIncremental opts mode cache globalGraph mains =
  RelinkResult
    { rrBundle = assembleBundle opts (Map.elems fragments),
      rrCache = fragments,
      rrRegenerated = regenerated,
      rrReused = reused
    }
  where
    Opt.GlobalGraph graph _ _ = globalGraph
    reachable = Map.keysSet graph
    partitions = partitionByModule graph

    resolved :: Map ModuleName.Canonical (ModuleFragment, Bool)
    resolved = Map.mapWithKey resolveModule partitions

    fragments = Map.map fst resolved
    regenerated = Map.keysSet (Map.filter snd resolved)
    reused = Map.keysSet (Map.filter (not . snd) resolved)

    -- Returns (fragment, wasRegenerated).
    resolveModule home nodes =
      let !hash = moduleContentHash mode nodes
       in case Map.lookup home cache of
            Just cached | mfHash cached == hash -> (cached, False)
            _ -> (generateFragment mode mains graph reachable home nodes, True)
