import type { CompilationResult, CompilationError, PlaygroundFile } from '../types';

const API_ENDPOINT = '/api/compile';

const MOCK_COMPILATION_ENABLED = true;

export async function compileCanopy(files: PlaygroundFile[]): Promise<CompilationResult> {
  const mainFile = files.find(f => f.name.endsWith('.can'));
  if (!mainFile) {
    return {
      success: false,
      errors: [{
        line: 1,
        column: 1,
        message: 'No Canopy source file found',
        severity: 'error',
      }],
    };
  }

  if (MOCK_COMPILATION_ENABLED) {
    return mockCompile(mainFile.content);
  }

  try {
    const response = await fetch(API_ENDPOINT, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        files: files.map(f => ({ name: f.name, content: f.content })),
      }),
    });

    if (!response.ok) {
      throw new Error(`Compilation server error: ${response.status}`);
    }

    return await response.json() as CompilationResult;
  } catch (error) {
    return {
      success: false,
      errors: [{
        line: 1,
        column: 1,
        message: error instanceof Error ? error.message : 'Unknown compilation error',
        severity: 'error',
      }],
    };
  }
}

function mockCompile(source: string): CompilationResult {
  const errors: CompilationError[] = [];
  const startTime = performance.now();

  const lines = source.split('\n');
  let hasModule = false;
  let moduleName = 'Main';

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lineNum = i + 1;

    if (line.trim().startsWith('module ')) {
      hasModule = true;
      const match = line.match(/module\s+(\w+)/);
      if (match) {
        moduleName = match[1];
      }
    }

    if (line.includes('undefined')) {
      errors.push({
        line: lineNum,
        column: line.indexOf('undefined') + 1,
        message: 'Use of `undefined` is forbidden. Use proper Maybe/Either types.',
        severity: 'error',
      });
    }

    if (line.includes('fromJust')) {
      errors.push({
        line: lineNum,
        column: line.indexOf('fromJust') + 1,
        message: 'Use of `fromJust` is forbidden. Use pattern matching or `maybe`.',
        severity: 'error',
      });
    }

    const parenBalance = (line.match(/\(/g) || []).length - (line.match(/\)/g) || []).length;
    if (parenBalance > 0 && i === lines.length - 1) {
      errors.push({
        line: lineNum,
        column: line.length,
        message: 'Unclosed parenthesis',
        severity: 'error',
      });
    }

    if (line.match(/^\s*let\s+.*=\s*$/)) {
      errors.push({
        line: lineNum,
        column: 1,
        message: 'Incomplete let binding',
        severity: 'error',
      });
    }
  }

  if (!hasModule) {
    errors.push({
      line: 1,
      column: 1,
      message: 'Missing module declaration. Add: module Main exposing (..)',
      severity: 'error',
    });
  }

  const compilationTime = performance.now() - startTime;

  if (errors.length > 0) {
    return {
      success: false,
      errors,
      compilationTime,
    };
  }

  const jsOutput = generateMockJavaScript(source, moduleName);

  return {
    success: true,
    output: jsOutput,
    compilationTime,
  };
}

function generateMockJavaScript(source: string, moduleName: string): string {
  const lines = source.split('\n');
  const functions: string[] = [];
  const types: string[] = [];

  for (const line of lines) {
    const funcMatch = line.match(/^(\w+)\s*:/);
    if (funcMatch) {
      functions.push(funcMatch[1]);
    }

    const typeMatch = line.match(/^type\s+(?:alias\s+)?(\w+)/);
    if (typeMatch) {
      types.push(typeMatch[1]);
    }
  }

  let js = `// Generated by Canopy Compiler v0.19.1
// Module: ${moduleName}

(function(scope) {
  'use strict';

  var _${moduleName} = {};

`;

  for (const type of types) {
    js += `  // Type: ${type}\n`;
    js += `  function ${type}(value) {\n`;
    js += `    return { $: '${type}', value: value };\n`;
    js += `  }\n\n`;
  }

  for (const func of functions) {
    js += `  // Function: ${func}\n`;
    js += `  var ${func} = function() {\n`;
    js += `    // Compiled implementation\n`;
    js += `    return null;\n`;
    js += `  };\n`;
    js += `  _${moduleName}.${func} = ${func};\n\n`;
  }

  js += `  // Main entry point
  if (typeof _${moduleName}.main !== 'undefined') {
    if (typeof document !== 'undefined') {
      document.addEventListener('DOMContentLoaded', function() {
        var app = _${moduleName}.main(document.body);
        if (app && typeof app.init === 'function') {
          app.init();
        }
      });
    }
  }

  scope.${moduleName} = _${moduleName};
})(this);
`;

  return js;
}

export function validateCanopySyntax(source: string): CompilationError[] {
  const errors: CompilationError[] = [];
  const lines = source.split('\n');

  let bracketStack: { char: string; line: number; col: number }[] = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lineNum = i + 1;

    for (let j = 0; j < line.length; j++) {
      const char = line[j];
      if (char === '(' || char === '[' || char === '{') {
        bracketStack.push({ char, line: lineNum, col: j + 1 });
      } else if (char === ')' || char === ']' || char === '}') {
        const expected = char === ')' ? '(' : char === ']' ? '[' : '{';
        const last = bracketStack.pop();
        if (!last || last.char !== expected) {
          errors.push({
            line: lineNum,
            column: j + 1,
            message: `Unexpected '${char}'`,
            severity: 'error',
          });
        }
      }
    }
  }

  for (const unclosed of bracketStack) {
    errors.push({
      line: unclosed.line,
      column: unclosed.col,
      message: `Unclosed '${unclosed.char}'`,
      severity: 'error',
    });
  }

  return errors;
}
